### ISSUE TITLE
Allowing to have a sync_only or similar config, so that only the directories mentioned in sync_only will be synchronized, instead of reading through all the databases and checking if this folder should be skipped or not...

### ISSUE THREAD

**Issue by braindotai** [abraunegg/onedrive#1010]
**Is your feature request related to a problem? Please describe.**
So in my onedrive, there are a lot of folders and files... like more than 1.5TB, so of course it makes more sense to use `sync_list` config file to synchronize selectively... otherwise it would take months 😬. But the problem with `sync_list` is that even though I've provided the directories to be sync, it still goes through all the directories and then checks should this dir be skipped or not... Thus wasting a lot of time

For example:
```
Skipping item - excluded by sync_list config: abc
Processing 224 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
Processing 214 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
Processing 238 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
Processing 238 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
Processing 239 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
Processing 243 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
Processing 238 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: abc
.....
```
Like even if I wanted to synchronize just one folder in my OneDrive, it sill takes a full 3 days :(

**Describe the solution you'd like**
So I think there should another config file, like `sync_only`, and the `--synchronize` will only do through the directories listed in this config file. Instead of going through all the directories...

**Comment by abraunegg** [comment]
@braindotai 
As you do not specify what version you are running, 'sync_list' performance handling was improved 10x by https://github.com/abraunegg/onedrive/pull/992 

Unfortunately, due to how OneDrive API works, and how the original client was written, when files / folders that were excluded, are now included, this will be *missed* and never downloaded, if a full walk of the online OneDrive folder is never done.

This is the trade off ... nothing can be done about this.

Please re-try any testing you have been doing by using 'master' if you have not already done so.

**Comment by braindotai** [comment]
@abraunegg thanks for your response. I'm using `v2.4.3-17-g2fe0574`, yeah I guessed that its onedrive api's limitation. Though could you suggest any other way... to sort of solve this issue... from outside the scope this api. Like may be by some setting in my onedrive account etc...

**Comment by abraunegg** [comment]
@braindotai 
The *only* other alternative option here is - dont use `sync_list` ..... use `--single-directory 'path'`

I say this because then you are not constrained by the 'sync_list' issues around changes made on OneDrive online to include / exclude folders in / out of scope.

If you are have many directories in your 'sync_list' file, create a file that is not called 'sync_list', then write a shell script that calls the client recursively with `--single-directory 'path'` with each path as listed in this file.

It is not as 'elegant' as a full solution - but .. will be way faster syncing 1 directory over 'sync_list' and even multiple, if you have massive amounts of data on OneDrive online.

**Comment by 3ntranced** [comment]
I am trying this, when I specify a folder within onedrive that has 1 file, it takes like 30 minutes, and dont even end up with that file. Here is my command
`onedrive --verbose --synchronize --download-only  --single-directory 'Documents/Office Lens'`

Most of the output is like this
`Remote change discarded - not in --single-directory sync scope (not in DB)`

**Comment by abraunegg** [comment]
@3ntranced 
Please do not respond to a closed case, and open a new issue please for assistance.
