### ISSUE TITLE
Question: How to keep only one newest version with service

### ISSUE THREAD

**Issue by TDHTTTT** [abraunegg/onedrive#1019]
I am running onedrive as a system service. I noticed when I open the same pdf on my laptop and tablet, it will create another files for different version. So, is it possible to force update the files and keep only whichever file that is newest?

**Comment by abraunegg** [comment]
@TDHTTTT 
> I noticed when I open the same pdf on my laptop and tablet, it will create another files for different version. So, is it possible to force update the files and keep only whichever file that is newest?

This is a known 'bug' in the 'skilion' client. What client version are you running?

What do your log files tell you as to why a second version is being created?

If the log files are specifying that a new version is being created due to data preservation, you can disable this in the configuration file:
```
bypass_data_preservation = "true"
```

However use this option with extreme caution.

**Comment by TDHTTTT** [comment]
Thanks for the quick reply! It is working for me as I want!
