### ISSUE TITLE
Sharepoint upload sync fails as free space isn't read correctly

### ISSUE THREAD

**Issue by dunkelgruen** [abraunegg/onedrive#1036]
Thanks a ton for your great work! Works like a charm, really love it. Think I found a minor bug, though:
I am trying to synchronize with a sharepoint folder. Download works fine, upload is refused with the error message:
`ERROR: OneDrive account currently has zero space available. Please free up some space online.`
and
`Updated Remaining Free Space: 0`
...although there is plenty of space and creating new files and uploads work fine with other apps and in the browser.

I _think_ the reason might be, that I am not the "owner" of the sharepoint folder and cannot read the quota as a normal user. (I am not that much into MS stuff, though ...)
Any ideas how to solve this?

**Comment by abraunegg** [comment]
@dunkelgruen 
Please can you update your post with all the required details as per the support requirements. Your post is missing critical details to assist in a timely manner - such as version details and a verbose debug log - all of which are requested when using the bug report template.

Additionally, this issue sounds like https://github.com/abraunegg/onedrive/issues/1028 which is already fixed in master - but without all the required details, I cannot say for sure at this point.

**Comment by dunkelgruen** [comment]
Sorry for the lacking information! Not used to bug reporting...
Thanks for the hint, I tried your fix from #1028 - works like a charm now: file upload works, same warning as stylersnico.
Thanks a lot!
If I can help with any additional testing/logs/etc. let me know.

**Comment by abraunegg** [comment]
@dunkelgruen 
No problem - just make sure you build from 'master' and not use the PR - as thats a static point in time fix, and you then would be missing all the other fixes pre / post that one as well.

Glad that this is resolved for you, closing issue.
