### ISSUE TITLE
Remove restriction end directory name to match 'Icon'

### ISSUE THREAD

**Issue by idachev** [abraunegg/onedrive#1037]
When my last directory is ending with `Icon` the tool reports this:
`Skipping item - invalid name (Microsoft Naming Convention): test/Icon`

I found this check in the code:
`if (itemName == "Icon") {matched = false;}`

https://github.com/abraunegg/onedrive/blob/206ab8f516bbe8e524782e0e35c43219351a0661/src/util.d#L198

Why this is done?

How to solve this issue?

I cannot force my directories to never be named `Icon`

**Comment by abraunegg** [comment]
@idachev 
> Why this is done?
This was due to the limitations that Microsoft have implemented and documented at the time when this bug was fixed.

As you have looked in the code, higher up in that function are the URL's that specify restrictions and limitations:
* https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN
* https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us

This is where this 'Icon' check came from - to be in compliance with these requirements.

This being said, [Invalid file or folder names](https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us#invalidfilefoldernames) section now no longer lists 'Icon' as a invalid folder name ... 

> How to solve this issue?

I have just tested a PR to resolve this issue, and the folder creation does not generate an error any more (it used to).

Please can you test the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1038/head:pr1038
git checkout pr1038
./configure; make clean; make;
```

**Comment by idachev** [comment]
I tested it with the latest update in the docker image and it works:
driveone/onedrive             latest                5c59b51c759e        3 days ago          661MB
