### ISSUE TITLE
cannot sync a specific folder

### ISSUE THREAD

**Issue by kalexiou** [abraunegg/onedrive#1058]
Hi,

I want to synchronize a local folder (email_20200902) that is already present in Onedrive in the cloud. Since this folder is not inside my OneDrive local root directory but 3 levels lower (local path of the folder to synchronize: `OneDrive/dir1/dir2/dir3/email_20200902`), I am using a `sync_list` file where I have added the parent directory of the email_20200902 folder:

`.config/onedrive/sync_list:`

`dir1/dir2/dir3/`

This is the command I am using, from my home directory (/home/kalexiou)

`onedrive --synchronize --upload-only --local-first --single-directory email_20200902 --syncdir /media/kalexiou/Dades/OneDrive/ --resync`

and these are the output messages

`Configuration file successfully loaded`
`Configuring Global Azure AD Endpoints`
`Initializing the Synchronization Engine ...`
`Syncing changes from selected local path only - NOT syncing data changes from OneDrive ...`
`Uploading differences of email_20200902`
`Uploading new items of email_20200902`

Still the update of the folder in the cloud is not happening. The test file that I want to add is called `test.txt`.

I will appreciate any help!

Thanks
Kostas

**Comment by abraunegg** [comment]
@kalexiou 

There are several issues with what you are trying to do.

1. Unless you are changing where all your data resides locally, and if you care about potential data loss, be very very very careful when using `--syncdir` option. Because your are changing the syncdir, this is why you also need the `--resync`
2. Do not use 'sync_list' to achieve this - this is why you need to also use `--resync`. Be very careful here, as, because you are using `--syncdir` option this might lead to undesirable consequences for future sync's - and may lead to data loss of your data as system has lost what the correct sync state is and where your data is, because of the other options you are using.

**Suggestion:**
* Reconfigure your client, taking away all the 'crazy' configuration from above
* The path you want to sync is `OneDrive/dir1/dir2/dir3/email_20200902`
  * I am going to assume here the full local path will be `~/OneDrive/dir1/dir2/dir3/email_20200902`
  * Your config file 'sync_dir' is set to '~/OneDrive'
  * The folder exists on OneDrive, but it does not exist locally
  * The folder exists on OneDrive in the following path: `/dir1/dir2/dir3/email_20200902`
* Run the following command:
  * `onedrive --synchronize --single-directory '/dir1/dir2/dir3/email_20200902' --upload-only --local-first --verbose --dry-run`

The `--single-directory` input is 'relative' to your existing OneDrive 'sync_dir' config. By trying to 'sync_list' or change the directory on the fly will just cause undesirable effects.

The above command should:
* Create the local path `~/OneDrive/dir1/dir2/dir3/email_20200902` if it does not exist
* Sync any data the local folder `~/OneDrive/dir1/dir2/dir3/email_20200902` to OneDrive online 

If the `--dry-run` operation performs what you are attempting to achieve, remove the `--dry-run` and sync your data.

If you are still having issues, please generate a debug log for support as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by kostasgalexiou** [comment]
Thanks @abraunegg for the fast and detailed reply!
