### ISSUE TITLE
How to upgrade from 'skilion' version on Ubuntu bionic

### ISSUE THREAD

**Issue by mczakk** [abraunegg/onedrive#1060]
hi @abraunegg,
i am using the old version of this software, and it is incredibly useful so i want to keep using it. Unfortunately when i try and update i get the following ,message : 
```
http://ppa.launchpad.yann1ck/onedrive/ubuntu bionic release 404 not found.
```
please could you explain to a relative novice how to update to your version?

Many Thanks

**Comment by abraunegg** [comment]
@mczakk 
Unfortunately the PPA does not support 'bionic'.

Your best solution is to follow all the sections within https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md for your Ubuntu platform / version.

The high level steps are:

* Uninstall any 'onedrive' package you have installed
  * `<sudo> apt remove onedrive`
* Determine if you are running i686 or x86_64 version of Ubuntu - given that 'bionic' supports both architectures .. you need to know this
* Follow either, depending on your architecture
  * [Install dependencies for i686](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x--lubuntu-18x--debian-9---i386--i686)
  * [Install dependencies for x86_64](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64)
* [Compile and Install](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation)

**Comment by abraunegg** [comment]
Closing issue, question answered

**Comment by mczakk** [comment]
Thanks, but i have two further questions:
will the command <sudo> apt remove onedrive remove the files downloaded to my ubuntu machine by the previous incarnation of onedrive?
The instructions in your link do not reference ubuntu 20.04, which is what i am running, will this be an issue?

**Comment by abraunegg** [comment]
@mczakk 
You said you were running the 'skilion' version .. so who knows what or how you installed that, You also said you were running Ubuntu 'bionic' which, is 18.x, which, most likely you installed the 'skilion' version from a package. This is why I advised to clean this up. If it is not installed, not a problem.

> The instructions in your link do not reference ubuntu 20.04, which is what i am running, will this be an issue?

The instructions do reference Ubuntu 20.x ... please re-read. 

> onedrive --version
> returns
> onedrive v2.4.3-16-g928ad95
> so i guess it is installed? (It still works btw)

That is an old version, built from 'master' .. so .. at some point you followed the instructions to build from source.

> i'm guessing i need this version - 2.4.4-0202008121743ubuntu20.04.1 


That is the PPA version. It has issues due to the LDC compiler.

Build from source as per the instructions, install as per the instructions, and when you are complete you should have:
```
onedrive v2.4.5-11-g4ddad0c
```
