### ISSUE TITLE
Authorization need Admin Approval?

### ISSUE THREAD

**Issue by rikow** [abraunegg/onedrive#1067]
Dear all,

I upgraded today the onedrive client from 3.13 (Ubuntu repos) to latest (4.4) from the ppa.
When I followed the link to authorize the client, I was informed that it needs Admin Approval. That was not the case with the old version.

So I asked my admin to follow the link and he sent me the URI generated. That did in fact authorize the client, however uploaded files and folders did not end up under my onedrive account. And we couldn't figure out, WHERE it ended up. I did manage to remove the remote files and we closed that authorization, since it was not clear which door we have opened.

Anyone else experienced that and knows who do deal with it? This is a business account.

Thanks and cheers, Riko

**Comment by abraunegg** [comment]
@rikow 

> When I followed the link to authorize the client, I was informed that it needs Admin Approval. That was not the case with the old version.

This is due to that the client identifier was updated, along with the authorisation scopes to be compatible with the OneDrive API changes. Please refer to https://github.com/abraunegg/onedrive/issues/835 for more details.

> So I asked my admin to follow the link and he sent me the URI generated. That did in fact authorize the client, however uploaded files and folders did not end up under my onedrive account. And we couldn't figure out, WHERE it ended up. I did manage to remove the remote files and we closed that authorization, since it was not clear which door we have opened.
> 
> Anyone else experienced that and knows who do deal with it? This is a business account.

This sounds very much like your data ended up on the OneDrive account you performed the admin approval authorisation with - so that would have been the business administration account. Some browsers - and I have noticed this with Chrome myself - caches the OneDrive login, even though you do not save the password, thus, when you when to 'authorise' the client, the previously used credentials were utilised - thus, plausible explanation as to where your files went.

Now that the updated client identifier has been 'approved' by your organisation, if you now authenticate the client correctly (clearing any stored credentials or even using a different browser), your data will go to your OneDrive account from the updated client.

**Comment by abraunegg** [comment]
Closing issue as question answered
