### ISSUE TITLE
Excluded folders checking consumes a lot of time

### ISSUE THREAD

**Issue by ClimberBear** [abraunegg/onedrive#1077]
I'm running onedrive synchornizations on Ubuntu 20.04.

Versión: onedrive v2.4.5-16-g19cf656

In my onedrive, I have an internal folder for backup purposes, with a lot of files. I have excluded from syncronizaction using both config and sync_list

My config:

```
jmalbarran@irulan:~/.config/onedrive$ cat config 
# upload_only = "false"
# check_nomount = "false"
check_nosync = "true"
# download_only = "false"
# disable_notifications = "false"
skip_symlinks = "true"
skip_dir = "Backup"
```
My sync_list

```
# Include / Exclude folders to sync
# Include
Dropbox
# Exclude
!Backup
```
But, when I run
`onedrive --synchronize --verbose`

I takes a very, very long time because it checks the Backup folder (excluded intentionally) a lot of times. This is an extract from output:
```
Processing 303 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
Processing 301 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
Processing 322 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
```

### Bug Report Details ###
**Describe the bug**

**Application and Operating System Details:**
Ubuntu 20.04
```
uname -a
Linux irulan 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
*   Are you using a headless system (no gui) or with a gui installed?
No
*   OneDrive Account Type
Onedrive Business Account
*   Did you build from source or install from a package?
Built from source

*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
```
dmd --version
DMD64 D Compiler v2.093.1
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.5-16-g19cf656
Config path                            = /home/xxxxxxxx/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = true
Config option 'sync_dir'               = /home/xxxxxxxx/OneDrive
Config option 'skip_dir'               = Backup
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
# Include / Exclude folders to sync
# Include
Dropbox
# Exclude
!Backup

Business Shared Folders configured     = false
```

*   Provide the version of curl you are using: Output of `curl --version`
```
curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
Local directory
*   Provide all the mountpoints in your system: Output of: `mount`

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install onedrive as user service
2.  Restart machine with shutdown -r now
3.  Check status with systemctl status onedrive@xxxxxx
4.  See error

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@ClimberBear 
There are several items that need to be addressed here.

### 1.  Folders being synced and excluded

From your configuration, you are forcing the sync to only ever sync 'Dropbox', which would be in the path of `~/OneDrive/Dropbox` and exclude everything else including everything else online.

What you are *way* better off doing is *not* using 'sync_list' here. 

By using 'sync_list' you will *force* the client to check every single object that is stored on OneDrive every time the client performs a sync. This is done as, the OneDrive API as zero capability to understand your 'client side exclusions' thus, you need to check all objects for all changes.

If your usage scenario is that you *just* want to sync the 'Dropbox' folder, and that you want to exclude any 'Backup' folder, you need to reconfigure your client in this manner:
* Remove 'sync_list' file
* Leave your 'skip_dir' configuration as is
* Sync your data with the following command: `onedrive --synchronize --verbose --single-directory 'Dropbox'`

This will give you the following benefits:
* Faster sync's as the client can now utilise correct tracking of changed data because you are not using 'sync_list'

Test the above command via:  `onedrive --synchronize --verbose --single-directory 'Dropbox' --dry-run`

If you wish to then utilise the `--single-directory 'Dropbox'` with `--monitor` and systemd services, you will need to manually edit your systemd service file to add the correct directives.

### 2.  Log message: Processing XXX OneDrive items to ensure consistent local state due to sync_list being used

Due to your existing configuration, this is why you are seeing this:
```
Processing 303 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by skip_dir config: Backup
```

This is 100% normal and to be expected.

**Comment by ClimberBear** [comment]
Hi

I'm trying after removing the sync_list file, but now, when I execute

NOTE: I had to add --resync, it requested it!

`onedrive --synchronize --verbose --single-directory 'Dropbox' --dry-run --resync`

I get a lot of log lines saying:
```
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
Remote change discarded - not in --single-directory sync scope (not in DB)
```

And, again, takes a lot of time

**Comment by ClimberBear** [comment]
More info:

I have tried to run in real (without the --dry-run) and I get an error. How can I reset all?

```
onedrive --synchronize --verbose --single-directory 'Dropbox' --resync
Using 'user' Config Dir: /home/jmalbarran/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/xxxxxxxxx/OneDrive
Application version: v2.4.5-16-g19cf656
Account Type: business
Default Drive ID: b!b4izurk2tUqv0ImhUSmhNM9PVhnBUbVGljSX07AjEneXAWpoV-LjQoaC_4pYSQlF
Default Root ID: 01HQV2MVV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 988167093229
Fetching details for OneDrive Root

A database statement execution error occurred: disk I/O error

Please retry your command with --resync to fix any local database corruption issues.
```

**Comment by abraunegg** [comment]
@ClimberBear 
> I have tried to run in real (without the --dry-run) and I get an error. How can I reset all?

The client should be cleaning up all temporary files on restart / rerun.

Can you please provide an `ls -la` of the configuration directory please:
```
ls -la /home/xxxxxxxx/.config/onedrive
```
where xxxxxxxx is your user

**Comment by abraunegg** [comment]
> Hi
> 
> I'm trying after removing the sync_list file, but now, when I execute
> 
> NOTE: I had to add --resync, it requested it!
> 
> `onedrive --synchronize --verbose --single-directory 'Dropbox' --dry-run --resync`
> 
> I get a lot of log lines saying:
> 
> ```
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> Remote change discarded - not in --single-directory sync scope (not in DB)
> ```
> 
> And, again, takes a lot of time

This is 100% normal. The first sync (and any sync using --resync), the local database file needs to be populated with all the required data.

Subsequent sync's will be faster as you are not using 'sync_list'

**Comment by ClimberBear** [comment]
Sorry, but second time I have the same problem (a lot of messages "Remote change discarded". and a lot of time.

The content of my config folder is:
```
xxxxxxxxxx@hhhhhh:~/.config/onedrive$ ls -la
total 5040
drwxrwxr-x  2 xxxxxxxxxx xxxxxxxxxx    4096 sep 30 14:13 .
drwx------ 24 xxxxxxxxxx xxxxxxxxxx    4096 sep 19 21:55 ..
-rw-rw-r--  1 xxxxxxxxxx xxxxxxxxxx     175 sep 20 13:28 config
-rw-rw-r--  1 xxxxxxxxxx xxxxxxxxxx     175 sep 20 13:28 .config.backup
-rw-rw-r--  1 xxxxxxxxxx xxxxxxxxxx      28 sep 20 13:28 .config.hash
-rw-r--r--  1 xxxxxxxxxx xxxxxxxxxx  946176 sep 30 14:16 items.sqlite3
-rw-r--r--  1 xxxxxxxxxx xxxxxxxxxx   32768 sep 30 14:16 items.sqlite3-shm
-rw-r--r--  1 xxxxxxxxxx xxxxxxxxxx 4148872 sep 30 14:17 items.sqlite3-wal
-rw-rw-r--  1 xxxxxxxxxx xxxxxxxxxx    1078 sep 30 14:13 refresh_token
```

Important topic is that in this machine I have also the monitor service installed, but previously to run the synchronize, I stopped with
`systemctl stop onedrive@xxxxxxxxxx.service`

**Comment by abraunegg** [comment]
@ClimberBear 
> Important topic is that in this machine I have also the monitor service installed, but previously to run the synchronize, I stopped with
> `systemctl stop onedrive@xxxxxxxxxx.service`

If you are attempting to run 2 instances of the client at the same time - this is what will cause database corruption. Do not run the client as a service & try and run the client in standalone mode (--synchronize ) at the same time ... this will also lead to error messages such as 
```
A database statement execution error occurred: disk I/O error`
```
If you are still getting this error:
1. Stop all 'onedrive' processes
2. Manually remove `items.sqlite3-shm` & `items.sqlite3-wal` files
3. Restart application


Re: 
```
Remote change discarded - not in --single-directory sync scope (not in DB)
```

This is 100% normal. What this indicates is a 'change' (new file, modified file, new folder, modified folder, file or folder deletion) event occurred outside the current sync scope you have specified.

The OneDrive API sends you 'all' changes. There is zero way to filter this out 'server side' (on OneDrive itself), thus, every change from the last sync has to be processed (because this is what the API returns) for inclusion or exclusion based on what you have configured to be in scope.

**Comment by abraunegg** [comment]
Closing issue, question answered

**Comment by ClimberBear** [comment]
> Closing issue, question answered

Understood the issue. The API send always all changes. But, in this case, how is managing this the windows/mac client? Thy synchronize (omitting ofeending folder) really quick.
In any case, thanks foe your work, and sorry for the inconvenience!
