### ISSUE TITLE
Add switch to disable logfile

### ISSUE THREAD

**Issue by spacecowboy** [abraunegg/onedrive#108]
It would be useful to have a switch to disable the logfile completly when running the systemd service. 

If I'm running the systemd service, then I want the logs in journald (which printing to stdout/stderr achieves) and not another separate logfile. Especially when I run the service in user mode and don't have write access to /var/log

**Comment by abraunegg** [comment]
This is better worked into the 3.x.x version where the whole application is being re-written

**Comment by abraunegg** [comment]
@spacecowboy 
Can you please help test this PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/239/head:pr239
git checkout pr239
make
make install
```

This PR provides the following enhancements:
* Change '--download' to '--download-only' to align with '--upload-only' 
* Change the logging to a separate file to not be the default so that excessive disk I/O does not occur (Issue #158)
* Close out Feature Request #108, by only enabling the local logfile when '--enable-logging' is used
* Close out Feature Request #212 by adding a new configuration option to specify the logging directory

To use a different log directory, add the following to `~/.config/onedrive/config`:
```
log_dir = "/path/to/location/"
```
Trailing slash required

**Comment by spacecowboy** [comment]
@abraunegg I'm no longer working at the place where they used Onedrive so can't help. Sorry :(

**Comment by abraunegg** [comment]
PR #239 merged
