### ISSUE TITLE
reexport to cifs possible? incremental file updates for ms-office formats?

### ISSUE THREAD

**Issue by kaizimmer1** [abraunegg/onedrive#1117]
Hello,
i have two questions about this onedrive client:
- is it possible to reexport onedrive folder to cifs or samba clients (without risk data loss)?
- microsofts onedrive supports incremental file updates for ms office file formats (only), does this client too?

**Comment by abraunegg** [comment]
@kaizimmer1 
> is it possible to reexport onedrive folder to cifs or samba clients (without risk data loss)?

You can redirect your 'sync_dir' location to a mounted CIFS location - not a problem, however then you will lose the capability to use 'inotify' for `--monitor` operations. CIFS, NFS, NTFS etc does not support (and never will support) inotify - so what will happen is that realtime upload of changes will not occur, and uploads will only be done every sync loop.

> microsofts onedrive supports incremental file updates for ms office file formats (only), does this client too

Whilst this is the case, this is because of NTFS and other factors in their control. Incremental updates are not supported - and wont be.

**Comment by abraunegg** [comment]
Closing issue as question answered
