### ISSUE TITLE
Syncing multiple shared folders from Sharepoint

### ISSUE THREAD

**Issue by Mebus** [abraunegg/onedrive#1146]
Hallo,

is it possible to sync multiple shared folders from Sharpoint and my personal OneDrive folder at the same time? I only found in the docs, that it is possible to sync one Sharepoint shared folder. Unfortunately, it also syncs my personal folder with the shared Sharepoint folder, when I sync.

Is there a solution to this?

Mebus

**Comment by abraunegg** [comment]
@Mebus 
> is it possible to sync multiple shared folders from Sharpoint and my personal OneDrive folder at the same time? 

Yes it is, however you need to have separate configurations for each SharePoint Site Library that you wish to sync. This includes then changing the `sync_dir` path for each configuration so that the path where this data is stored is also changed.

>  Unfortunately, it also syncs my personal folder with the shared Sharepoint folder, when I sync.

For each configuration, you need to then include / exclude using `sync_list` what you want to sync with each configuration. Feel free to submit a new feature request to sync 'just' the SharePoint Site Library.

**Comment by liolio6** [comment]
Hello 
I created one config file for each Sharepoint
How to use it with onedrive command ?

In config files I have
sync_dir = "/mountpoint"
drive_id = "b!Ko1pSezVT0KwCP......"
for my two Sharepoint in directory ~/.config/onedrive/

Thanks for your help

**Comment by abraunegg** [comment]
@liolio6 
You need to have multiple configuration directories for each configuration file. Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts for further details.

**Comment by abraunegg** [comment]
Closing issue as original question answered
