### ISSUE TITLE
Use Implied Grant to Login

### ISSUE THREAD

**Issue by wpinedailabaca** [abraunegg/onedrive#1147]
I don't know if this is an idea or a how-to question.

I have an Azure VM, linux ubuntu 18.04. From time to time I have to log in again since the login has an expiration period. Is there a way to use implicit Grant, using certificates and secrets? Do I think this could automate the login?

**Comment by abraunegg** [comment]
@wpinedailabaca 
This is not possible due to the authentication methods for OneDrive:
* https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/authentication?view=odsp-graph-online


> From time to time I have to log in again since the login has an expiration period

You only need to login again if:
* You change your password
* If your 'access token' does not get refreshed within the usage period

I suspect that the issue you are facing is due to the second point, meaning your VM or app was stopped, thus, the token got expired. This is not something I can change.

**Comment by abraunegg** [comment]
Closing issue as question answered
