### ISSUE TITLE
don't know how to login

### ISSUE THREAD

**Issue by taylortianwei** [abraunegg/onedrive#1155]
Hi there,

When I tried to login to sharepoint, I got an issue like:
```
$onedrive
Authorize this app visiting:

xxxxxxxxxxxxx

Enter the response uri: xxxxxxxxxx

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: b3b69294-7a62-429f-981b-e77224074100
Correlation ID: 8ce8dda9-59b5-4add-9ffc-5fc3a6cf2cd2
Timestamp: 2020-11-20 01:24:38Z

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.
```
-----------------------------

Would be grateful if someone could help me with this.

**Comment by abraunegg** [comment]
@taylortianwei 
There are 2 issues here:

1. You have a bad response from OneDrive, hence the 400 error response. This is probably because you are running a older version of the application which contains an authentication bug.
2. You are not specifying the correct parameters to use the application

To resolve your issue, please review:
* [Install Guide](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md)
* [Usage Guide](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md)

Additionally, as you have not also used the [Issue Template](https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md) you are missing other critical information to help assist you quickly - this is why there is a Bug Report Template .. next time please use it. Can you please update your first post with the missing information.
