### ISSUE TITLE
Local file (with newer content) was sync'd with stale remote content after login issues

### ISSUE THREAD

**Issue by pd5rm** [abraunegg/onedrive#1169]
### Bug Report Details ###

**Describe the bug**

1. I changed my OneDrive password due to corporate password rotation policies.
2. I didn't realize this had stopped OneDrive from syncing (no UI notification AFAIK) and continued working with content on OneDrive path (a single text file).
3. After about 10 days, I saw that the client was repeatedly crashing. I believe the trace was similar to [this](https://github.com/abraunegg/onedrive/issues/401) ticket.
4. I didn't make the connection to password change, but figured I'd update to latest build to see if it fixes it. I upgraded to a custom PPA version of 2.4.7-0 from 2.3.13-1build2 (latest version on on 20.04 Ubuntu release).
5. I then saw the comment about using --logout flag to reset the auth token. I made the connection to password change, and reset the auth token and pasted the new URI.
6. I ran the onedrive --synchronize command.
7. I saw that it pulled the cloud version (stale) of the file from 10 days ago and overwrote the local file (**lost data!**).

I couldn't find any 'logs' in /var/log/onedrive.

**Application and Operating System Details:**
*  Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
   * Ubuntu 20.04.
*   Are you using a headless system (no gui) or with a gui installed?
    * Gnome
*   OneDrive Account Type
    * Business account I think.
*   Did you build from source or install from a package?
    * Package offered by distro (Ubuntu)
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`
    * 2.3.13
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.3.13
Config path                            = /home/<username>/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/<username>/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

*   Provide the version of curl you are using: Output of `curl --version`
    * 7.68
*   Is your configured 'sync_dir' a local directory or a network mount point?
    * Local.
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
    * ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
    * Only in use on one system. Just sync'd to cloud.

**Additional context**

I haven't done the debug logs, repro steps, verbose output that were requested, since the issue has already occurred, and things appear to be working fine now.

 I've also upgraded to Ubuntu 20.10 which has a newer (v2.4.4-1,but not the latest version) of OneDrive.

I'd like to better understand the sync mechanism.

1. How can a local file with newer metadata (modified time etc)  get replaced with a stale cloud version?
2. Why wasn't there a 'conflict' file created to contain both the cloud and local versions if they're mismatched?
3. Is there any way to recover the lost content (I didn't see a version in the OneDrive web site that correspond to my updates).

Finally, I wanted to thank you personally for providing timely updates and maintaining this project. ;-)

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [ ] Reproduction steps (if applicable)
*   [ ] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@pd5rm 
Your issue is because you are running old client versions which are stale and contain bugs. You need to upgrade your client.

Do not use the Ubuntu Packages, unless the Ubuntu PPA has the updated package for your platform. Please also note, the Ubuntu package (PPA or other) also contains *other* isssues, such as:
* Service file issues
* Crashing due to how the client is built as a package using LDC

If the available packages for your platform are not at least the latest release, you need to build from source.

> I saw that it pulled the cloud version (stale) of the file from 10 days ago and overwrote the local file (lost data!).
As for your exact issue:
* You are running old code. You are bound to run into issues, especially if you are running v2.3.x series. You need to upgrade.
* You tried to upgrade to 2.4.x series, but for whatever reason you are still running old code, as `--version` still shows v2.3.x
* Your experienced data loss - not good, but no doubt this is one of the comparison bugs that was fixed. However, *whenever* a local file is replaced by a remote file, and finds the local file to be conflicting - the client moves the existing file to a new file name as a 'backup' to *prevent* data loss. Check your local files to ensure that the renamed file exists. If this is *not* the case - I need your entire log output from the event to try and work out what is going on.

In short, you need to be running v2.4.8 or greater. The Ubuntu packages are behind (and are broken in many ways). Either use the Debian packages directly which are known to be good, or become the package maintainer for Ubuntu and fix the shenanigans that come with the Ubuntu packaging process.

To upgrade your client:
#### Remove Ubuntu Package
```
sudo apt autoremove onedrive
```
#### Remove Ubuntu PPA
```
sudo add-apt-repository --remove ppa:yann1ck/onedrive
```

#### Build from source fro Ubuntu 20.x
Install dependencies as per [instructions](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64 ):
```
sudo apt install build-essential
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
sudo apt install pkg-config
sudo apt install git
sudo apt install curl
sudo apt install libnotify-dev
curl -fsS https://dlang.org/install.sh | bash -s dmd
```
Clone the repository, compile and install:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
./configure
make clean; make;
sudo make install
```

**Comment by abraunegg** [comment]
@pd5rm 
Additionally, to answer your further questions:

> I'd like to better understand the sync mechanism.
>
> 1. How can a local file with newer metadata (modified time etc) get replaced with a stale cloud version?

It should not be replaced. The code, when it finds a mis-matched local file for whatever reason, the local file is renamed to preserve the data. This 'preservation' can be bypassed by setting `bypass_data_preservation = "true"` within your config file. If you do this, you know the consequences of such action - potential data loss. If you have not set this, you need to check your local sync_dir folder for the renamed file.

The renamed file will be in the form of:
```
<original-name>-<hostname>.<file-extention>
```
> 2. Why wasn't there a 'conflict' file created to contain both the cloud and local versions if they're mismatched?

There should be, see above.

> 3. Is there any way to recover the lost content (I didn't see a version in the OneDrive web site that correspond to my updates).

Your file should be on your local file system as a renamed item.

> I couldn't find any 'logs' in /var/log/onedrive.

You dont say how you are normally running the application - via a systemd file or manually all the time?

If you have not set to log application output, by setting `enable_logging = "true"` or passing in `--enable-logging` there will be no local log file created. The exception here is if you are using systemd normally, then, systemd will contain various logs:
```
journalctl --user-unit=onedrive -f
```
or 
```
journalctl --unit=onedrive@<username> -f
```

**Comment by abraunegg** [comment]
Closing issue fro the following reasons:
* Ubuntu package, old code version being used, issue invalid
* Questions answered

**Comment by pd5rm** [comment]
Hi there, just to followup on this.

- I've removed all traces of distro versioned OneDrive packages.
  - apt-get purge onedrive as well (I would think this would be similar to rm -f  step above)
- Replaced with git source version (onedrive v2.4.8-1-g4a68eb4)
  - This was surprisingly easy as you've done a great job with autoconf scripts and instructions for dependencies above.
  - I wasn't able to use Debian package as it had a dep on some other pacakge, and I didn't want to go down a path of mixing 2 distro deps.
- I wasn't able to find a backup file. ;-(
- I did see logs via journalctl and only found these sort of items related to my missing todo.txt file:
```
Nov 20 17:31:14 hp705 systemd[1924]: onedrive.service: Failed with result 'signal'.
Nov 20 17:31:14 hp705 systemd[1924]: onedrive.service: Main process exited, code=killed, status=11/SEGV
Nov 20 17:31:14 hp705 onedrive[1933]: Got termination signal, shutting down db connection
Nov 20 17:31:14 hp705 systemd[1924]: Stopping OneDrive Free Client...
Nov 20 17:30:30 hp705 onedrive[1933]: Syncing changes from OneDrive ...
Nov 20 17:29:54 hp705 onedrive[1933]: skipped.
Nov 20 17:29:54 hp705 onedrive[1933]: Uploading modified file notes/todo.txt ...
Nov 20 17:29:54 hp705 onedrive[1933]: Skipping item - OneDrive returned a 'HTTP 401 - Unauthorized' when attempting to query if file exists
Nov 20 17:29:54 hp705 onedrive[1933]: Moving notes/.goutputstream-TRPGU0 to notes/todo.txt
Nov 20 17:29:54 hp705 onedrive[1933]: skipped.
Nov 20 17:29:54 hp705 onedrive[1933]: Uploading modified file notes/todo.txt ...
Nov 20 17:29:44 hp705 onedrive[1933]: Remove your '/home/<username>/.config/onedrive/items.sqlite3' file and try to sync again
Nov 20 17:29:44 hp705 onedrive[1933]:   Error Reason:  Access token has expired.
Nov 20 17:29:44 hp705 onedrive[1933]:   Error Message: HTTP request returned status code 401 (Unauthorized)

```

**Comment by abraunegg** [comment]
@pd5rm 

> I wasn't able to find a backup file. ;-(

This is 100% *really* odd, as, even going back to the 'skilion' code branch with those bugs, whenever there is an existing local file of the same name, looking to be updated by remote content, a backup file is created.

Unfortunately none of your logs show a 'download', where the local file is being replaced. In the code, this is where the safe rename occurs when the attempt to download conflicts. When there is a new upload attempt, the local file is the source of truth, no backup is made on the cloud as - you are uploading the file there.

I suspect that your issue is 100% compounded by:
* Use / choice of Ubuntu
* Use of Ubuntu package & old binaries

However, as you are now not using the Ubuntu package / old binary - I suspect you will not run any further issue when your password expires / password changes in the future.

To ensure that you are notified on your desktop when this event occurs, reconfigure your client as follows if you have not already done so:
```
./configure --enable-notifications
make clean; make;
sudo make install
```

Additionally, ensure that you use `--verbose` in any systemd configuration file. You will need to modify the installed systemd service files to add this in on the `ExecStart=` lines as this is *not* the default. This will ensure that there is more verbosity in any journalctl entry. Use also a config file, enable logging to have a 2nd reference of all client activity.

Lastly, to ensure that you also keep your client up-to-date, you need to watch this GitHub repository so that you get notified of new releases (typically monthly, can be slightly more frequent, sometime less - but on average monthly) so that you can rebuild your client to get the latest version with any bug fixes / enhancements and not run a stale 12 month old client which you were doing.

**Comment by pd5rm** [comment]
All good suggestions above. Thanks again for maintaining this project and for the incredibly thoughtful and detailed comments you've provided throughout this ticket.
