### ISSUE TITLE
My .DOCX Was Overwriten With 0 Bytes

### ISSUE THREAD

**Issue by brandonkirsch** [abraunegg/onedrive#1171]
### Bug Report Details ###
**Describe the bug**
I spent three hours working on a .DOCX file yesterday while saving changes locally to a folder monitored by the Onedrive script.  When I was done with my changes, I saved the document one last time and closed out of Word.  When I went to send my .DOCX as an email attachment, the filesize was 0 bytes.  My onedrive logs (towards bottom) indicate that a timeout occurred on O365 during one of the intermediate sync operations.  I believe the onedrive script mishandled this error and overwrote my .DOCX with an empty file.

**Application and Operating System Details:**
*   Fedora 32 / Linux BKirsch-T490S 5.9.10-100.fc32.x86_64 #1 SMP Mon Nov 23 18:12:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   GUI + Docker container
*   OneDrive Account Type: O365 for Business
*   Did you build from source or install from a package?  Docker package
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version` N/A
*   OneDrive Application Version: Output of `onedrive --version`  onedrive v2.4.3-14-g76ce103
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```onedrive version                       = v2.4.3-14-g76ce103
Config path                            = /root/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

*   Provide the version of curl you are using: Output of `curl --version`  curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
*   Is your configured 'sync_dir' a local directory or a network mount point?  Local directory.
*   If *not* local, provide all the mountpoints in your system: Output of: `mount` N/A
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` EXT4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

I am running Windows 10 with Office 365 in a KVM VM.  It has access to my Linux host filesystem via Samba share.
I edit documents using O365 in the VM and save them over Samba to my host FS.  
The host has the onedrive script running in a docker container.  Its logs shows several saves that were synced to O365, but then a "timeout" occurs which I've inferred to mean Microsoft Office 365 timeout (and not something local on my machine.)  
After the timeout, the onedrive script *deletes* the .DOCX out from under me while I'm working on it, then seems to get confused on its next actions:  it alternates between "syncing new file" and "syncing file differences."
At the end of my work session, I hit "Save" in Word before closing out.  By the time I got to my inbox to email the document, the .DOCX showed 0 bytes filesize.
For what it's worth, I am **not** running any 3rd party virus scanners on Windows VM or Linux host.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
I cannot reproduce this behavior. I've never seen a "timeout error" or had any of my Office documents replace with a 0 byte size.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

File path on host:  `/home/bkirsch/dev/projects/Notes/00 OneDrive/General/Projects - Preliminary/City Electric` 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading modified file General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx ... skipped.
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading modified file General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx ...  done.
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 1DBD680
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading modified file General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx ... skipped.
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new file General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx ... done.
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Deleting item from OneDrive: General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new file General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx ... done.
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [N/A] Reproduction steps (if applicable)
*   [N/A] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@brandonkirsch 
As a first port of call, please upgrade your client / Docker image. You are running old code. Docker should be telling you that there is a new version available and you should be upgrading. Major releases are ~monthly, current is v2.4.8. Please upgrade your client ASAP. Additionally please can you implement some sort of 'upgrade check' to upgrade your Docker image when new releases are done.

> The host has the onedrive script running in a docker container. Its logs shows several saves that were synced to O365, but then a "timeout" occurs which I've inferred to mean Microsoft Office 365 timeout (and not something local on my machine.)

Correct. This timeout is with Curl accessing OneDrive to perform an API action. This error can also be 'simulated' with a HTTPS firewall rule on the appropriate endpoint to block HTTPS traffic briefly. This is how I test error capturing for these sort of scenarios.

> After the timeout, the onedrive script deletes the .DOCX out from under me while I'm working on it, then seems to get confused on its next actions: it alternates between "syncing new file" and "syncing file differences."

Actually the client cannot do this. It cannot delete a local file after upload unless the following 3 conditions met:
* The file was uploaded to OneDrive without error, and the file was queried, file size / hash between the two match
    - This is done for every upload regardless, to validate what was uploaded is correct as per the local file to ensure data integrity
* The `--upload-only` flag is set
* The `--remove-source-files` is set

The client cannot also make a file '0 byte' post an upload, so any zero byte file has to come from somewhere else.

Now - looking at the code in depth, when attempting to *download* a new file from OneDrive, if the local file does not exist or in conflict, a new file will be created, opened as read/write before data is downloaded - and at that small point in time, the new file *is* zero bytes in size. None of your current logs however show trying to download a file.

> I am running Windows 10 with Office 365 in a KVM VM. It has access to my Linux host filesystem via Samba share.
I edit documents using O365 in the VM and save them over Samba to my host FS.

OK ... I am assuming Office 365 local install on Windows 10 or are you using Office365 online?

> At the end of my work session, I hit "Save" in Word before closing out. By the time I got to my inbox to email the document, the .DOCX showed 0 bytes filesize.

There are a number of different other areas of potential failure here:
1. Samba version and how it is handling writes / multi access to files
2. The underlying file system that Samba is using to store your data - how is it handling I/O control to your files between the VM and Docker reading it
    - Docker / Linux VM might not be able to understand any open filesystem open locks that the open file may have
3. How is Windows 10 handling the open file handle / file stream of your open document & saving that file to 
4. Is the Windows 10 OneDrive client configured / installed and potentially syncing this data as well?
5. Entire local OS / configuration stack in the virtualisation layer between KVM & the local OS and Docker. I have seen instances where the local networking stack glitches in this sort of situations due to high local I/O load or hitting some sort of high watermark. In this situation, local network access to other systems / services briefly can get reset.
    - In this sort of scenario, how is your Docker instance seeing the local files - will this see the actual files through the virtualisation layer or will the files be presented as zero byte / no access ... 

Now looking at your logs that you have provided:

>```
>Uploading new items of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
>Deleting item from OneDrive: General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
>Uploading differences of General/Projects - Preliminary/City Electric/City Electric Statement of Work DRAFT.docx
>```

This is *really* interesting. This tells me:
1. Uploaded new data
2. Deleted a file
3. Uploaded new data

So what caused the *file deletion* ?

The onedrive client:
* Checks the cache file for the sync state
* Checks if the file exists on the local file system
* If the file has *gone* from the local filesystem, the client tells OneDrive to remove the file

So ... what told the onedrive client that the file was *gone* or that the file was now deleted:
* The local filesystem?
* The way that Windows 10 writes to network shares?
* The way that MS Office / Office 365 handles reading / writing files to disk or network shares, or the way that Samba interprets this?
    - This sounds *very* similar to https://github.com/abraunegg/onedrive/issues/712 where WPS office would *delete* the file, then re-create the file when saving updates / changes ... similar to your scenario

What was the file size *during* this activity / event? That would be very interesting to understand. The only way however to see that data is via verbose debug log.

#### Questions:
1. What version of Samba? What OS / Version is this running on?
2. What is your configuration of Samba for the shared folder?
3. What is the underlying filesystem that Samba is using / folder being shared out from?
4. What SMB authentication is being used between Windows 10 and the Samba share?

#### Potential reproduction steps (for you to confirm):
1. Configure OneDrive to use a folder, which is shared out via Samaba
2. Have the onedrive client sync this Linux folder, run client in full debug mode
3. Use an Office 365 local install on a VM to edit a file and keep the file open, writing data to it, having the file upload via Linux / VM / Docker
4. Keep file open, but on Docker or Linux block HTTPS traffic with a firewall rule, generate a timeout accessing OneDrive
5. Write new data to open MS Word file, save file post the timeout
6. Updated file *should* be uploaded, with correct / new filesize and not a zero byte file size

#### Potentially 'better' workflow (for you to consider):
* Windows 10 -> Windows 10 OneDrive Client 'push' new file from VM file system (non SMB share) to OneDrive
  * This way Windows is handling the I/O control of access to your data, when you have the file still open and modifying it
* Linux VM pulls down changes and saves in the configured sync_dir path


I will try and replicate this scenario, as it does not sound good and *should* not happen, however I am also flagging this as an invalid issue as you are running old code.

If I cannot replicate this at all or even something similar - I will have to put this down to some sort of local environment issue. Unless, you can come back with verbose debug logs that show something more concrete as to what is occurring from the client there is really *very* little else that can be done if I cannot replicate this situation. I do suspect something in your environment caused this, and this is *not* a client issue or bug.

In the meantime, actions for you:
1. Upgrade your Docker / Client version
2. Modify your Docker / Client configuration so that you are running `--verbose` at a minimum, and if possible, full debug via `--verbose --verbose`
3. Implement some sort of 'upgrade check' to upgrade your Docker image when new releases are done

**Comment by brandonkirsch** [comment]
Since this morning I realized that I have not been correctly pulling new / latest images of my Docker images for a very long time.  I am now running `onedrive v2.4.8-1-g4a68eb4`

Also, I mis-spoke about `the onedrive script deletes the .DOCX` as the file was never missing from my PC.  It was simply 0 bytes, perhaps for the reason we see in #712.  Another piece of evidence that supports this theory:  the versioning in O365 Sharepoint is completely fresh for this file, as if it were brand new and did not have any prior revisions that we see in the log. Perhaps I can recover some revision of my document from a Trash or Recycle Bin in Sharepoint.

    What version of Samba? What OS / Version is this running on?  Fedora 32 / 4.12.10
    What is your configuration of Samba for the shared folder? I'm using the "home folder" feature built into /etc/smb.conf.  Relevant snippets:
```
[global]
        workgroup = Fenwick
        server string = BKirsch-T490S Fedora 31
        security = user

        passdb backend = tdbsam

        printing = cups
        printcap name = cups
        load printers = yes
        cups options = raw

        browseable = Yes
[homes]
        comment = Home Directories
        valid users = %S, %D%w%S
        browseable = Yes
        read only = No
        inherit acls = Yes
```
    What is the underlying filesystem that Samba is using / folder being shared out from? EXT4
    What SMB authentication is being used between Windows 10 and the Samba share? I'm not sure how to tell. I'm entering my local Linux host credentials to access the Linux-hosted SMB share.

I have changed my onedrive client to use --upload-only and debug modes enabled.  I will try to spend some time tomorrow reproducing this issue as instructed.

**Comment by abraunegg** [comment]
@brandonkirsch 
Suggest, from a Samba perspective, you do the following:
```
client min protocol = SMB3
client max protocol = SMB3
```

This makes sure you are using at least the right Windows SMB version for Windows 10 to access Samba. It may make however other systems (Linux etc) no longer connect to Samba unless they too support SMB3. Many legacy Linux devices only support SMB1 which is very bad (security issues, read/write issues and the like).

I would also *strongly* suggest you implement this: [Samba VFS Recycle Bin](https://www.samba.org/samba/docs/current/man-html/vfs_recycle.8.html)
* The vfs_recycle intercepts file deletion requests and moves the affected files to a temporary repository rather than deleting them immediately. This gives the same effect as the Recycle Bin on Windows computers.

In the event a file is being requested to be deleted - you have somewhere where you can recover this file from.

> Perhaps I can recover some revision of my document from a Trash or Recycle Bin in Sharepoint.

There are 2 levels of trash / bins from memory when using SharePoint / OneDrive Business accounts. You *may* be lucky in that regard.

**Comment by brandonkirsch** [comment]
Thank you for this excellent information regarding Samba.  I truly appreciate your support and the wealth of information you have shared.

Also: I just found _three_ old copies of this document in the Sharepoint Recycling Bin!!  It was a bit tedious, but I was able to restore one of the copies and then use the Sharepoint Versioning feature to restore 100% of my lost work.  What a shame that due to deadlines I spent all of my afternoon rewriting that document before I found the old one in the trash :( 

I think it is safe to say that I have been bitten by #712.  Thanks again for all of your support.
