### ISSUE TITLE
OneDrive generates a 'Invalid API or resource' error message

### ISSUE THREAD

**Issue by abraunegg** [abraunegg/onedrive#1174]
When running the current client, the following error will be generated:
```
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
Uploading differences of ~/OneDrivePersonal
Uploading new items of ~/OneDrivePersonal

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
(dmd-2.093.1)[alex@centos7full onedrive]$ 
```

This is a OneDrive API regression, and has been flagged for Microsoft to review & advise here: https://github.com/OneDrive/onedrive-api-docs/issues/1408

This issue *only* impacts OneDrive Personal Accounts at present, and has not been experienced with OneDrive Business / Office365 accounts.

This issue started approx 8th December 2020.

**Comment by zhouweitong3** [comment]
Same issue here.

**Comment by abraunegg** [comment]
@zhouweitong3 
> Same issue here.

Please redirect your comment to the above API docs link. There is nothing I can do here, and this issue I have raised here is merely for visibility

**Comment by abraunegg** [comment]
For *anyone* who is experiencing this issue, this has now been fixed by Microsoft.

However, to *fix* your client, you need to perform a `--resync` operation to get back into a error free sync process. This is due to how the application currently handles / stores the badly formatted deltaLink response from Microsoft.

I am looking at a fix in code for this situation at present as well.

**Comment by abraunegg** [comment]
For those users who have been 'hit' by this bug, if you do not want to perform a `--resync`, please use PR #1175 
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1175/head:pr1175
git checkout pr1175
./configure; make clean; make;
```

When running this PR version, your client version will be `onedrive v2.4.8-2-g04c845b` or greater

If you feel comfortable to install this, make sure you perform a `make install` as well.

What this PR will do is - when the API fails due to this issue, it will reset the cached deltaLink value, thus on next use, get the new / updated deltaLink avoiding the issue that Microsoft created.

This will avoid you having to perform a `--resync` which will also fix the issue.

**Comment by lahtis** [comment]
I have a few files on OneDrive cloud. The all have been synced to my computer. I went to copy one file from Onedrive’s web interface and edited it libreoffice and then uploaded it to the cloud via a browser in second computer. When I synced with the app then an error occurred. Im a normal user. Onedrive version is 2.4.8, Ubuntu 18.04.5 LTS

my logs are:
onedrive --synchronize
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...

ERROR: OneDrive returned an error with the following message:
Error Message: HTTP request returned status code 400 (Bad Request)
Error Reason: Invalid API or resource
Uploading differences of ~/OneDrive
Uploading modified file Carpenter/sold.ods ... done.
Uploading new items of ~/OneDrive

ERROR: OneDrive returned an error with the following message:
Error Message: HTTP request returned status code 400 (Bad Request)
Error Reason: Invalid API or resource

If you've modified the Linux machine files from any defect has not been previously entered. Sync has worked seamlessly in the cloud. Otherwise, the files will be synced to the correct cloud service. Even if an error message appears.

**Comment by lahtis** [comment]
im testing PR #1175 and i have a --resync files. And now onedrive working ok.

**Comment by abraunegg** [comment]
@lahtis 
If you are running PR #1175, you do *not* need to use `--resync`

**Comment by abraunegg** [comment]
PR merged into 'master'

**Comment by abraunegg** [comment]
Keeping open for visibility

**Comment by abraunegg** [comment]
Closing issue

**Comment by Joel-max-s** [comment]
I don't know if it belongs here.
I just downloaded, compiled and installed this Onedrive client.
When i try to authentiacate i get this error:
`Request Id: 73daa070-8203-4a96-8611-eddc0fb10501
Correlation Id: 116c0707-98ad-4adb-8bad-875035754166
Timestamp: 2020-12-09T20:07:06Z
Message: AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.`
I logged in on an other machine 4 days ago and everything was fine, since yesterday on an other machine it does'nt work.

**Comment by abraunegg** [comment]
@Joel-max-s 
Please open a new issue following the correct support proceedure as detailed here: https://github.com/abraunegg/onedrive#reporting-issues

Required:
1. Use the bug report template
2. Full verbose debug log to analyse what is going on
