### ISSUE TITLE
--single-directory behavior is not same as sync_list

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#1182]
While --single-directory works fine, I observe that if I use sync_list with only one dir in it, onedrive always do excessive item processing, is that expected?  Synchronization is over 1 minute even when there's no files changed.

"Processing 205 OneDrive items to ensure consistent local state due to sync_list being used" will appears over one hundred times per each sync.

Application version: v2.4.8-3-g3b18638
[log1.txt](https://github.com/abraunegg/onedrive/files/5700763/log1.txt)

**Comment by abraunegg** [comment]
@priv 
> While --single-directory works fine, I observe that if I use sync_list with only one dir in it, onedrive always do excessive item processing, is that expected? Synchronization is over 1 minute even when there's no files changed.

This is to be expected. 100% normal behavior.

The reason is as follows:
1. When using 'sync_list' due to how OneDrive API tracks changes, a moved object that is moved into or out of scope can be missed
2. When using 'sync_list', because of the above, using the /delta response is not possible, thus, all objects need to be iterated though due to point 1

When using `--single-directory` - a /delta call can be made against that specific directory, capturing all changes correctly, thus leading to faster processing.

This is *not* a bug or issue.

**Comment by priv** [comment]
Thanks!
