### ISSUE TITLE
Specifiying target directory in OneDrive to Sync

### ISSUE THREAD

**Issue by najum98** [abraunegg/onedrive#1203]
Hello, first of all, I would like to appreciate your effort for building this amazing tool.

I have read the docs but I am unable to know that how can I specify that which directory from onedrive should be synced, I mean sync_dir is for local directory but what if I want to store the data from local directory to a specific directory on OneDrive and sync only from that specific directory. How's that possible? Thank you

**Comment by najum98** [comment]
Like I am using a single one drive account on multiple PCs so I have made specific folders for each PC and I dont want this to mess up. Data should go to one specific directory

**Comment by abraunegg** [comment]
@najum98 
Due to *how* the actually OneDrive API works, what you are wanting to achieve is not possible out of the box, but, *is* possible with configuration of your local system to utilise your desired remote directory structure.

The *only* way this will work is as follows:

**Assumptions:**
* Remote OneDrive folder structure:
```
├── Remote_PC_1
├── Remote_PC_2
├── Remote_PC_3
├── Remote_PC_4
└── Remote_PC_5
```

**Local PC 1 Configuration:**
* Make a local directory within ~/OneDrive correlating with Remote_PC_1
* Ensure your sync_dir remains as `~/OneDrive`
* Store all your data that you wish to upload to OneDrive *only* in Remote_PC_1 directory
* Utilise the `--single-directory` parameter when syncing
  * Example: `onedrive --synchronize --single-directory 'Remote_PC_1'`
  * Example: `onedrive --monitor --single-directory 'Remote_PC_1'`
* Test with `--dry-run` to ensure this is operating correctly


**Local PC 1 Advanced Configuration:**
* Create an alternate location for 'sync_dir' eg: `/files/OneDrive`
* Create in that directory the correlating directory for Remote_PC_1
* Update the configuration file 'sync_dir' parameter for the new 'root' location `/files/OneDrive`
* Create a symbolic link of `/files/OneDrive/Remote_PC_1` to `~/OneDrive`
  * Example: `ln -s /files/OneDrive/Remote_PC_1 /home/alex/OneDrive`
* Store all your PC_1 files in the home directory OneDrive folder (~/OneDrive), and this will get synced when using `--single-directory` parameter because of the symbolic link
* Utilise the `--single-directory` parameter when syncing
  * Example: `onedrive --synchronize --single-directory 'Remote_PC_1'`
  * Example: `onedrive --monitor --single-directory 'Remote_PC_1'`
* Test with `--dry-run` to ensure this is operating correctly

If you then wish to use the systemd files to setup automatic syncing, you *must* then update the systemd configuration files with the required update:
```
ExecStart=/usr/local/bin/onedrive --monitor
```
  becomes:
```
ExecStart=/usr/local/bin/onedrive --monitor --single-directory 'Remote_PC_1'
```

If this all works, then repeat for all local PC's.

**Comment by najum98** [comment]
Hello, I am really thankful for such a detailed response. 

I implemented the steps you mentioned above, --dry-run worked as expected and I edited the systemd file as well
Now, when I check **systemctl --user status onedrive** it shows that the service is running but I cant see any changes being done on Onedrive, I added/removed some files from sync_dir to check if it is being synced in the background but nothing has appeared so far.

Apparently, the service is running but I dont know why it is not syncing.

Again, thankful for your guidance, I suggest you add the your reply mentioned above in the guide so that it helps others as well

**Comment by abraunegg** [comment]
@najum98 

> But a weird thing is happening, the data from some other remote directory is being synced to two locations in my PC, one in OneDrive and other in /Documents folder. This is really strange

Increase verbosity of the client with `--verbose` and double check your configuration on each / every system. Also enable logging to ensure you have log files of what is going on.

If there is something using `/Documents` you need to determine where this is coming from - misconfiguration or something else - maybe another client setup, Windows, other device.

**Comment by abraunegg** [comment]
Closing issue as original question answered
