### ISSUE TITLE
No Way for Installation on current Raspian on Raspi 3

### ISSUE THREAD

**Issue by lateralas** [abraunegg/onedrive#1287]
Hi,

I've been trying all day today to get this to work. Nothing works. First installed the app from the Raspi Repo. Works so far also up to the "Response_Uri" input. I get:
```
HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "cff86139-b0e4-4763-8771-15d7cd952d0c",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.
```
Is probably due to the old version in the repo. 
So compile it yourself. 
The Raspi does not have enough power for this and trying to install DMD or LDC brings "Unsupported Arch armv7l" errors.
So if you try to do this on a VM via crosscompiling, I get this back when I run:
```
./configure DC = ~/ldc2-1.16.0-linux-armhf/bin/ldmd2

checking for a BSD-compatible install ... / usr / bin / install -c
checking for pkg-config ... / usr / bin / pkg-config
checking pkg-config is at least version 0.9.0 ... yes
checking for dmd ... /home/pi/ldc2-1.16.0-linux-armhf/bin/ldmd2
checking version of D compiler ... /lib/ld-linux-armhf.so.3: No such file or directory

configure: error: Compiler version insufficient, current compiler version, minimum version 1.12.0
```
I just have too little idea to get that solved.
Can someone please help me with how I get the Programm work on a Raspi 3? 

Thanks

**Comment by abraunegg** [comment]
@lateralas 
Your issues relate to installing the 'onedrive' package from the repositories, which is non supported, and installing probably all sorts of other packages as well.

You can successfully compile on Raspbian on a Pi3. It has enough CPU power to compile. You need to ensure that you meet the required dependencies for compiling, including:
* Must have 1GB memory
* Must have 1GB swap space 

It is the last item that trips up *most* folk due to either reading too fast or not checking their system.

What you need to do:
1. Uninstall all packages that you have installed thus far, remove the 'onedrive' package
2. Cleanup all stale dependencies
3. Install the dependancies as per: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-raspbian-armhf
4. Build as per: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#armhf-architecture-raspbian-etc

The only other way is for you to become the Raspian package maintainer and update the package so that you can just install from the repo's.
