### ISSUE TITLE
Retry-After is not honored in case of HTTP response 429 Too many requests.

### ISSUE THREAD

**Issue by k6ps** [abraunegg/onedrive#1304]
### Bug Report Details ###
**Describe the bug**
I'm trying to download large amount of data (a few hundred GBs, mostly photos and videos, including a few large 2-3 GB files) from OneDrive after ending my paid subsrciption. At some point i started to receive HTTP error 429 - Too many requests. Noticed that this application does not honor the Retry-After header value sent, but instead tries again in 120 seconds. 

The command i was running:

```onedrive --synchronize --verbose --download-only --debug-https```

**Application and Operating System Details:**
*   system version: ```5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
*   standard Ubuntu 20.04 GUI
*   personal OneDrive account
*   installed from package
*   onedrive config: 
```
onedrive version                       = v2.4.10-0~202102221319~ubuntu20.04.1
Config path                            = /home/me/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/me/Data/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   curl version:
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   sync dir is local
*   sync drive partition type: ext4

Sent debug log via email to support@mynas.com.au

**To Reproduce**
I am not sure how to reproduce a 429 HTTP response. For me it happens regularily after i canceled my paid subscription and trying to download large amounts of data.

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [ ] Reproduction steps (if applicable)
*   [ ] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@k6ps 
I have reviewed your the log you have provided in email, however this log file is *not* a verbose debug log as required. Please follow the correct instructions for generating a debug log as per: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

In terms of your query as to not honoring the retry-after value, the code actually *does* check every response for a retry-after header value. 

Now - why is 120 seconds being used? This is because a 429 response was generated by the API, a retry-after header value was set, but the value was not used. When the 429 is handled, if the value is zero, a default of 120 is used. 

In your log file, I can see that the header is being set to `Retry-After: 4957` however why the code is not picking this up - unsure, as, the it should be checked and the value, as provided should be used

The only thing I can think of here is that *perhaps* Microsoft has changed the header response format. The header *used* to be `retry-after` but in your file it is `Retry-After` ... maybe ... 

Please can you generate a proper verbose debug log so I can see what is going on with the API responses.

**Comment by abraunegg** [comment]
@k6ps 
Many thanks for the updated debug log.

As per my email, please can you test the following PR to assist in resolving your issue, or at least it will provide some further insights as to why the retry-value is not being seen or used:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1305/head:pr1305
git checkout pr1305
./configure; make clean; make;
```
To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

When running the PR, your version should be: `onedrive v2.4.10-5-gb17a0d0` or greater.
