### ISSUE TITLE
Feature Request: Log Levels

### ISSUE THREAD

**Issue by jtrahan** [abraunegg/onedrive#1513]
I have my monitor to check for changes every 60 seconds so it's filling up my syslog with unnecessary messages every minute. It would be nice to have logging levels as an option.

Example
0 = No Logging
1 = Log Normal
 **Example Messages**
 Uploading differences of &lt;onedrive folder&gt;
 Uploading new items of &lt;onedrive folder&gt;
 Sync with OneDrive is complete

2 = Log ONLY changes. That would be files uploaded, downloaded, deleted
7 = Debug/Verbose

**Comment by abraunegg** [comment]
@jtrahan 
First question I have is - why are you checking for remote changes every 60 seconds?

The way the client works is, if you have many thousands of objects, every 60 seconds you are remotely checking OneDrive to iterate through all remote items, combined with re-validating all local disks items. Your local CPU will be constantly busy and this is extremely non-efficient. This also means the 'very' small window where local changes when using `--monitor` are actually able to be processed when their inotify actions are triggered.

Unless your data rate of change on OneDrive in the cloud actually is 60 seconds, there is absolutely zero reason for you to have this value so low, and this is why the default is 300 seconds which is a more reasonable timeframe, potentially in some environments 3600 seconds is even more reasonable.

> I have my monitor to check for changes every 60 seconds so it's filling up my syslog with unnecessary messages every minute. It would be nice to have logging levels as an option.

This is because you are basically causing this excess logging yourself by having the 'monitor_interval' so low.

By default, when using `--monitor` those messages that you have highlighted are actually only printed out every 5 times post initial startup. This logging output is also governed by the config option 'monitor_log_frequency'. Setting this value to say '60', in your scenario, would mean those messages are only displayed once an hour (because of your usage of a 60 second remote check), 24 times a day.

Please can you:
* Review why you are wanting 60 seconds for 'monitor_interval' as it is illogical in terms of how the client operates
* Configure 'monitor_log_frequency' to a setting > 5 - adjust as per required

**Comment by jtrahan** [comment]
Actually I have another workaround for my needs. I just created some rules in rsyslog to achieve what I wanted. I apologize I didn't think of this sooner.
