### ISSUE TITLE
Invalid UTF-8 sequence (at index 1)

### ISSUE THREAD

**Issue by remiOdite** [abraunegg/onedrive#1543]
My onedrive app suddenly stopped to work, getting this error message, when trying to synchronize, or perform anything else :

```
xxx:~/ $ onedrive --synchronize                                                                                                                            [11:37:18]
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
std.utf.UTFException@/snap/dmd/102/bin/../import/phobos/std/utf.d(1502): Invalid UTF-8 sequence (at index 1)
----------------
/snap/dmd/102/bin/../import/phobos/std/utf.d:1650 pure dchar std.utf.decodeImpl!(true, 0, const(char)[]).decodeImpl(const(char)[], ref ulong) [0x5563348db037]
/snap/dmd/102/bin/../import/phobos/std/utf.d:1144 pure @trusted dchar std.utf.decode!(0, const(immutable(char)[])).decode(ref const(immutable(char)[]), ref ulong) [0x556334951ac2]
/snap/dmd/102/bin/../import/phobos/std/utf.d:2890 pure @safe void std.utf.validate!(immutable(char)[]).validate(const(immutable(char)[])) [0x556334951a22]
/snap/dmd/102/bin/../import/phobos/std/file.d:577 @safe immutable(char)[] std.file.readText!(immutable(char)[], immutable(char)[]).readText(ref immutable(char)[]) [0x55633494f4bf]
src/onedrive.d:395 bool onedrive.OneDriveApi.init() [0x5563349a3487]
src/main.d:647 _Dmain [0x55633499bafc]

```

There is my onedrive version 
`onedrive v2.4.12-12-ge236c7c`

If anyone have an idea how to solve this, I'll be very grateful to him !

Regards,
Rémi

**Comment by abraunegg** [comment]
@remiOdite 
Whilst I appreciate you have an issue, this will be due to a particular file on your system. 

Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

What you are missing:
1. Using the bug report template
2. Debug log files
3. email containing debug log files + potentially the file that is causing the issue

Please create a new issue, following the correct process.
