### ISSUE TITLE
core-dump when "systemctl --user stop onedrive"

### ISSUE THREAD

**Issue by LWirmO** [abraunegg/onedrive#1609]
### Bug Report Details ###
**Describe the bug**
The log reports "core-dump" when using "systemctl --user stop onedrive" to stop the service

**Application and Operating System Details:**
*   xubuntu 20.04 LTS, Linux l7490 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   OneDrive Account Type Family subscription
*   Did you build from source or install from a package? used the opensuse.org apt according to the INSTALL.md instruction
*   OneDrive Application Version: Output of `onedrive --version` onedrive v2.4.13-1~np1
*   OneDrive Application Configuration: default
*   Explain your entire configuration setup - all default

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to 'terminal'
2.  Run 'systemctl --user stop onedrive'
3.  See error

Application Log Output:
```bash
Aug 21 09:29:54 l7490 systemd[2450]: Stopping OneDrive Free Client...
Aug 21 09:29:54 l7490 systemd[2450]: onedrive.service: Main process exited, code=dumped, status=11/SEGV
Aug 21 09:29:54 l7490 systemd[2450]: onedrive.service: Failed with result 'core-dump'.
Aug 21 09:29:54 l7490 systemd[2450]: Stopped OneDrive Free Client.
```

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@LWirmO 
Unfortunately this is not a bug or an issue I can solve.

The issue is caused by:
1. Your choice of Linux - Ubuntu
2. The package update policies of Ubuntu
3. How packages are build for Ubuntu
4. How the 'onedrive' package uses Ubuntu Universe LDC package for building the package for Ubuntu, on the SuSE Build Service

The technical root cause here is the Ubuntu 'ldc' package version - see https://github.com/abraunegg/onedrive/issues/1053 for further details. 

Your options to resolve:
1. Uninstall the 'onedrive' package and then build from source, following the correct instructions for your Ubuntu platform
2. Lodge a bug with the package maintainer for 'onedrive' and 'ldc' referencing this bug: https://bugs.launchpad.net/ubuntu/+source/ldc/+bug/1895969
3. Upgrade your Ubuntu to 21.x to determine if the issue still exists
4. Dont use Ubuntu or any of its derivatives - use a different Linux distribution

**Comment by abraunegg** [comment]
Updated documentation to explicitly reference this issue, as this is a known issue with the Ubuntu packages.

https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#2-on-ubuntu-2004-the-client-will-segfault--core-dump-when-exiting
