### ISSUE TITLE
Manage Onedrive folders with a GUI  

### ISSUE THREAD

**Issue by GiacomoDetomaso** [abraunegg/onedrive#1668]
**Problem**
This client is one of the best onedrive's client ever seen on Linux. The problem is that without a GUI the user experience may sometimes be frustrating, in particular for the users who do not feel comfortable by using a terminal. 

**Possible solution**
Build a **minimalist** UI. For example it could be used to configure accounts and sync changes without opening the terminal. This will make all the operations related to onedrive's folder faster and more user-friendly for unexperienced users.  

**Alternative**
A valid alternative idea could be, build some kind of shortcut that can let the user, sync the folders and do other "fast" operations with the client.

Thanks for the work you provide for this project!

**Comment by tanaga9** [comment]
I'm trying my own approach to that problem.
https://github.com/tanaga9/docker-onedrive-webui

I think the core(main) features and the GUI should be separated.

**Comment by abraunegg** [comment]
@JakDet 
> Build a minimalist UI. For example it could be used to configure accounts and sync changes without opening the terminal. This will make all the operations related to onedrive's folder faster and more user-friendly for unexperienced users.

Whilst I get the desire to have a GUI, this also extends to not learning how to do things beyond 'point-and-click' - it is your opportunity to self grow - to learn how to use Linux in different ways and become more experienced. 

For now, please review https://github.com/abraunegg/onedrive/wiki/External-Enhancements-to-the-OneDrive-Linux-Client for existing external enhancements - especially the system tray.

@tanaga9 
> I think the core(main) features and the GUI should be separated.

I appreciate your enthusiasm here, and agree that the GUI part should be a separate application, but I do not agree with your approach.

@JakDet 
Flagging your Feature Request as future work

**Comment by JakDet** [comment]
I agree with your opinion and many thanks for your answer.

**Comment by GalaxyCurse** [comment]
"Alternative
A valid alternative idea could be, build some kind of shortcut that can let the user, sync the folders and do other "fast" operations with the client."

I just have a shortcut on my desktop with
```
Name: Onedrive Updater
Comment: 
Command: onedrive --verbose --synchronize
Working Directory: /home/my-user-name/
Icon: Just an image of an Orce, I didn't find anything fitting for Onedrive
Options:
[  ] Use startup notification
[x] Run in terminal
```
I click it and a terminal pops up letting onedrive do it's thing and when finished, it disappears. 
I created it when I was on vacation and had to send files to my my home Linux computer for my wife to see.
At least for us, it works fine. It might help someone else.

**Comment by JakDet** [comment]
@GalaxyCurse i think that a Desktop Shortcut could be a valid solution. It may add some basic operation that should be fast and immediate to perform (like a sync for example)

**Comment by JakDet** [comment]
@GalaxyCurse I think it's a pretty good solution. Using DE shortcut (or a very minimalist UI) may let immediate operations (like a sync for example) faster and easier to perform for every kind of user. 

As @abraunegg said, keeping the focus on a terminal centered approach, could be a way, for unexperienced users to achieve a personal growth, and i totally agree with this. 

Even though the "main terminal infrastructure" has to keep a primary role for the application, i think that giving another way to perform the easiest operations, may be useful.

**Comment by TigerCubDen** [comment]
I consider the On-Demand feature should be go with GUI.

**Comment by tanaga9** [comment]
Isn't it the problem that CUI or GUI doesn't matter, and that the daemon (mode) doesn't exist?

Monitor mode is not a daemon because it requires interactive input.

For example, docker does not provide any interactive interface for dockerd (daemon), only API (for example, in /var/run/docker.sock).
docker's CUI is just a client, it just calls the API.

**Comment by abraunegg** [comment]
@TigerCubDen 
> I consider the configuration of On-Demand feature should be go with GUI.

This client does not support 'on-demand' functionality.

@tanaga9 
> Monitor mode is not a daemon because it requires interactive input.
Only for authentication - however the Docker configuration allows for specifying and using files and other items to *not* require interactive input to authenticate.

No interaction is needed once the client is operational - this is why it can be run as a systemd service as a daemon.

**Comment by TigerCubDen** [comment]
yes, I know. And it could be a future plan.

**Comment by SairusCZ** [comment]
Hey guys, 

I have really been enjoying @abraunegg 's OneDrive client. It really does work great, but I too was missing a bit more convenient way of configuring and monitoring it, especially when I'm just too busy and under pressure from other tasks. So, I made myself a little GUI prototype. I am a total newbie and this is my first project outside of scripting, but it has been fun. The GUI in its current buggy state supports login, tray-icon, basic configuration and file transfer monitoring.

Let me know what you think. 
-Should I share it on Github when it is in a bit more presentable state? 
-What about the layout, would you say it should be similar to the original Windows client, or more original?
-Any other ideas/suggestions/questions?

Preview: 
![ksnip_20220119-224228](https://user-images.githubusercontent.com/24818591/150219816-dcec86f6-ec54-4357-b3fc-9fc443178e83.png)

**Comment by GalaxyCurse** [comment]
@SairusCZ I love it and would use it. And even if others don't, well, it's up to them. If you share it on github, others might help make it better, or use it as it is.

**Comment by abraunegg** [comment]
@SairusCZ 
Awesome work there. I agree here with @GalaxyCurse - publish your code on GitHub, and do so sooner rather than later as then you will start getting feedback on aspects sooner - which may help shape / answer questions 'does this work' or 'should this be included' ?

One aspect I would like to see would be the ability for you to manage 'multi-configurations' & setups - so that from your 'current' settings window you have open - have:

* OneDrive Account 1 (or even allow the user to 'name this themselves'
* OneDrive Account 2  ...
* OneDrive Account X 

Then for each of these accounts:
* Ensure the configuration is in it's own unique .config directory
* Configure 'sync_list' in addition to the skip_file & skip_dir that you have now
* Enable / Disable the 'systemd' aspect of having the service automatically running
* Enable an easy way to start | stop | pause systemd services
* Flag if this is a Personal or Business account - if Business, allow further configuration such as allow the setting of the Drive ID to use (needed for SharePoint)
* If Business, enable | configure Business Shared Folders option
* Radio buttons to enable | disable config options that are true|false entries - not all, but ones that make sense such as:
  * upload_only (cant be used with download_only)
  * download_only (cant be used with upload_only)
  * local_first
  * dry_run
 

That way - those folk that have multi-accounts, can quickly configure / add a new account or even SharePoint site & configure basic options with a minimum of fuss


Kudos to you for starting work on this !!

**Comment by SairusCZ** [comment]
Thanks @abraunegg  for the feedback and tips. 

I originally was not planing for any of these features as I did not need them. But they make sense, so I did a few quick tests with multiple accounts and I think I can implement all points. I will just need to learn some new concepts to make it dynamically  scalable . 

I can't dedicate too much time to this right now, but I expect it to be shareable within a month. Hopefully less :-).

**Comment by diegocn** [comment]
Hey folks!
Great work here both on the CLI and the GUI prototype.
I was looking for a good onedrive CLI and loved how easy is to use/configure @abraunegg's one.
Also, would love to test/use @SairusCZ's GUI prototype and help evolving it.

**Comment by bpozdena** [comment]
Hey guys, the pre-release version of the GUI has been made available at https://github.com/bpozdena/OneDriveGUI . Please use the project page to report GUI related issues/questions/suggestions.

**Comment by GiacomoDetomaso** [comment]
> Hey guys, the pre-release version of the GUI has been made available at https://github.com/bpozdena/OneDriveGUI . Please use the project page to report GUI related issues/questions/suggestions.

Really nice! Congratulations!
