### ISSUE TITLE
What does missing "ability to encrypt/decrypt files on-the-fly when uploading/downloading files from OneDrive" mean?

### ISSUE THREAD

**Issue by andrewchen5678** [abraunegg/onedrive#1760]
What does missing "ability to encrypt/decrypt files on-the-fly when uploading/downloading files from OneDrive" mean? Does it mean the download and upload happen with http connection instead of https connection?

**Comment by abraunegg** [comment]
@andrewchen5678 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

This should have been opened as discussion rather than issue. Additionally, refer to https://github.com/abraunegg/onedrive/discussions/1333
