### ISSUE TITLE
CanT sync my account

### ISSUE THREAD

**Issue by Superpapotas** [abraunegg/onedrive#1822]
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "6a5ca6cc-3add-4cc7-a629-781d60285b1b",
    "error": "invalid_grant",
    "error_codes": [
        70000
    ],
    "error_description": "AADSTS70000: The provided value for the 'code' parameter is not valid.\r\nTrace ID: 9099c657-5e5c-47cd-989c-4f698bc3fe00\r\nCorrelation ID: 6a5ca6cc-3add-4cc7-a629-781d60285b1b\r\nTimestamp: 2022-01-30 08:07:33Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=70000",
    "timestamp": "2022-01-30 08:07:33Z",
    "trace_id": "9099c657-5e5c-47cd-989c-4f698bc3fe00"
}
----------------
??:? [0x55acd9b1a9d9]
??:? [0x55acd9b19cb5]
??:? [0x55acd9b1ab65]
??:? [0x55acd9b18f58]
??:? [0x55acd9b188c5]
??:? [0x55acd9b267a8]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fa28d3229db]
??:? _d_run_main2 [0x7fa28d3227ee]
??:? _d_run_main [0x7fa28d32265d]
??:? __libc_start_main [0x7fa28cf0e0b2]
??:? [0x55acd9af15ed]

**Comment by abraunegg** [comment]
@Superpapotas 
Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

Please note - this issue is most common because you are using Ubuntu. Please read the installation instructions *very* carefully.
