### ISSUE TITLE
Docker Image not up to date? / Operation not permitted error

### ISSUE THREAD

**Issue by wiphi** [abraunegg/onedrive#1847]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

Not possible, it runs from the docker container.

### Bug Report Details ###
**Describe the bug**
The docker image on docker hub is not up to date. The latest version is of onedrive in the container is `onedrive v2.4.13-7-g2b32c3a`.
I found a bug and want to test, if there is still present.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`: `Linux ddb4542bc03e 5.4.0-99-generic #112-Ubuntu`
*   Are you using a headless system (no gui) or with a gui installed? headless
*   OneDrive Account Type: Personal
*   Did you build from source or install from a package? Docker
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`: onedrive v2.4.13-7-g2b32c3a
*   OneDrive Application Configuration: Output of `onedrive --display-config`
*   Provide the version of curl you are using: Output of `curl --version`
*   Is your configured 'sync_dir' a local directory or a network mount point? local dir, shared with smb
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time: Multiple users, use in same time

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
Syncing files from different Clients and working on the same file with different users.
It happens offen with excel-files. The files will be delete without any reason.
It happens sometimes, when working on these files.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
2022-02-17T12:32:50.973530368Z ERROR: The local file system returned an error with the following message:
2022-02-17T12:32:50.973541837Z   Error Message:    Datei.xlsx: Operation not permitted
2022-02-17T12:32:50.973551407Z   Calling Function: downloadFileItem()
2022-02-17T12:32:50.973554862Z
2022-02-17T12:32:50.973558479Z
2022-02-17T12:32:50.973561931Z ERROR: The local file system returned an error with the following message:
2022-02-17T12:32:50.973565320Z   Error Message:    Datei.xlsx: No such file or directory
2022-02-17T12:32:50.973569434Z   Calling Function: applyChangedItem()
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

**Additional context**
I want to check if the bug already exists in the newest release, but dthe docker imge contains not the newest version.

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment]
@wiphi 

> The docker image on docker hub is not up to date. The latest version is of onedrive in the container is `onedrive v2.4.13-7-g2b32c3a`.
> I found a bug and want to test, if there is still present.

This is because Docker changed their policies and not prevent free / non-commercial entities from pushing code from GitHb to Docker. This occurred in the middle of 2021.

To build a more up-to-date Docker container, you must clone the GitHub repository and build your own Docker container locally using the updated code from GitHub. this is the only way at present.

Now to your problem:

> ```shell
> 2022-02-17T12:32:50.973530368Z ERROR: The local file system returned an error with the following message:
> 2022-02-17T12:32:50.973541837Z   Error Message:    Datei.xlsx: Operation not permitted
> 2022-02-17T12:32:50.973551407Z   Calling Function: downloadFileItem()
> 2022-02-17T12:32:50.973554862Z
> 2022-02-17T12:32:50.973558479Z
> 2022-02-17T12:32:50.973561931Z ERROR: The local file system returned an error with the following message:
> 2022-02-17T12:32:50.973565320Z   Error Message:    Datei.xlsx: No such file or directory
> 2022-02-17T12:32:50.973569434Z   Calling Function: applyChangedItem()
> ```

This indicates that something between Docker and your local filesystem is incorrect - permissions, file system type - something.

This is a local filesystem issue which you need to sort out first - I doubt building a new Docker image will fix this issue for you.

**Comment by wiphi** [comment]
Ok, thank you anyway. The local filesystem is a ext4 on a different hard drive. It's mounted via fstab
`/dev/disk/by-uuid/{uuid}/onedrive ext4 auto,defaults 0 2`
I didn't find any problem there....

**Comment by abraunegg** [comment]
> Ok, thank you anyway. The local filesystem is a ext4 on a different hard drive. It's mounted via fstab `/dev/disk/by-uuid/{uuid}/onedrive ext4 auto,defaults 0 2` I didn't find any problem there....

Just because you login to the system and do not find a problem - the issue will be that from inside Docker - the Docker user / Docker group potentially does not have the right permissions.

You are mounting the local file system via fstab - which mounts it as root.

What are the user|group permissions on the actual mount point?

If you 'su' to your Docker user, does your Docker user have access to that location?

If you login to the CLI of the Docker container - can what do you have access to? what errors are being detailed if any?

**Comment by abraunegg** [comment]
@wiphi 
> Is maybe the time-zone in the container maybe a problem? I've noticed that the logs are alyways 1h behind the time.

Certainly you need to fix the time within the Docker container - really important to ensure that time is in sync - as the file timestamp is one of the elements that is used to determine if a local file is newer or older and then analysed based on the hash of the time before making a final determination.

I would also ensure that your filesystem, of your mount is using ZFS - this then also ensures that you have a filesystem giving you true file integrity. EXT4 (or any other filesystem for that matter) does not give you this. For data that you care about, you should use ZFS - please educate yourself as to why. Additionally you could be hitting some obscure filesystem | race issue here as well because it is the filesystem that is returning the error that the operation is not permitted .. all the 'onedrive' client can do here is try the operation (which is what it does) and it cant (filesystem generated the error) so it reports that the filesystem gave an error.

**Comment by wiphi** [comment]
> @wiphi
> 
> > Is maybe the time-zone in the container maybe a problem? I've noticed that the logs are alyways 1h behind the time.
> 
> Certainly you need to fix the time within the Docker container - really important to ensure that time is in sync - as the file timestamp is one of the elements that is used to determine if a local file is newer or older and then analysed based on the hash of the time before making a final determination.

Okay, I fixed this by mounting `/etc/localtime:/etc/localtime:ro`. BTW: The docker logs are always in UTC. But the `date` function returns now the correct time.

> I would also ensure that your filesystem, of your mount is using ZFS - this then also ensures that you have a filesystem giving you true file integrity. EXT4 (or any other filesystem for that matter) does not give you this. For data that you care about, you should use ZFS - please educate yourself as to why. Additionally you could be hitting some obscure filesystem | race issue here as well because it is the filesystem that is returning the error that the operation is not permitted .. all the 'onedrive' client can do here is try the operation (which is what it does) and it cant (filesystem generated the error) so it reports that the filesystem gave an error.

If the error still persists, than I will try ZFS.

Thanks so much for your explaination and help!

**Comment by abraunegg** [comment]
@wiphi 
With the release of v2.4.18 - Docker containers are being automatically built and pushed to Docker Hub. Please check docker.md for updated Docker Tag details.
