### ISSUE TITLE
Feature Request: Preserve file/folder creation (not modified) timestamp

### ISSUE THREAD

**Issue by hyarsan** [abraunegg/onedrive#1887]
### Is your feature request related to a problem? Please describe.

OneDrive stores two potentially different file timestamps (`createdDateTime`, `lastModifiedDateTime`). This software only seems to preserve modified date, not creation date when synchronizing (downloading). Modified and creation dates also seem to be ignored for directories.

Is nanoseconds preserved? OneDrive's REST API documentation shows:
```json
"createdDateTime": "2014-10-31T03:37:04.72Z",
```
and the `.72Z` part is supposed to be nanoseconds.

### Describe the solution you'd like

File creation date is the same as visible on the OneDrive Web app, instead of current time when downloading. This could be an optional feature. Preserve modified (and creation) dates on directories.

### Describe alternatives you've considered

`rclone` doesn't support this either. Downloading a folder as a ZIP from the OneDrive Web app doesn't store the file creation date as the ZIP format doesn't support it.

### Additional context

Microsoft will delete files in a couple of months if I can't figure out how to do an exact copy of everything. I hope I can live without the creation dates...

Helpful info: https://en.wikipedia.org/wiki/MAC_times

**Comment by abraunegg** [comment]
@hyarsan 
> Preserve file/folder creation (not modified) timestamp

Unfortunately this is not going to be possible as 'D' does not have a function or capability to set the creationTime for files or folders on Unix platforms. The CreationTime can be queried - but only on Windows platforms, not supported on Unix. Refer to: https://dlang.org/library/std/file.html

To implement this, this would require:
* Changes to DMD | LDC itself to include functionality to query & a set function for that item

> I hope I can live without the creation dates...

Unfortunately you will have to live without the creation dates for your files and folders.

> Modified ~and creation~ dates also seem to be ignored for directories.

This is the *first* time this has been raised. What can be done is that when a folder is created, the online `lastModifiedDateTime`  can be used to set the modified time of the new local folder - but that is all that can be done.

> Is nanoseconds preserved?

They are not preserved due to historical reasoning (going back ~4 years) where not correctly obtaining the timestamp data of local items would cause items to be duplicated by the client, which, due to other bugs would cause local data loss.

It is potentially possible now that the zeroing of time fractions can be removed when performing comparison - however this potentially may have undesirable consequences. This being said however, fractional seconds are preserved when the modified timestamp is updated using the data from OneDrive API - for example:

```
[alex@centos7full OneDrivePersonal]$ ls -la --full-time
total 11124
drwxrwxr-x. 10 alex alex     4096 2022-03-15 10:56:17.588154494 +1100 .
drwx------. 41 alex alex     4096 2022-03-15 10:53:23.387847339 +1100 ..
drwx------.  5 alex alex      165 2022-03-15 10:56:53.880094213 +1100 3A
drwx------.  6 alex alex       62 2022-03-15 10:56:17.754163366 +1100 Documents
drwx------.  3 alex alex       28 2022-03-15 10:56:17.712161122 +1100 Dropbox
-rw-------.  1 alex alex       25 2022-01-11 08:19:00.725000000 +1100 fedora35_2.txt
-rw-------.  1 alex alex       25 2022-01-11 08:16:47.995000000 +1100 fedora35.txt
drwx------.  2 alex alex       26 2022-03-15 10:56:19.455254281 +1100 Images
drwx------.  2 alex alex       26 2022-03-15 10:56:18.620209653 +1100 Music
-rw-------.  1 alex alex      160 2021-11-23 12:01:52.154000000 +1100 newfile_locally-centos7full.txt
-rw-------.  1 alex alex       48 2021-11-23 11:35:46.132000000 +1100 newfile_locally.txt
-rw-------.  1 alex alex       28 2022-01-19 15:57:05.043000000 +1100 newfile.txt
drwx------.  2 alex alex        6 2022-03-15 10:56:03.534403422 +1100 random_files
drwx------.  4 alex alex       86 2022-03-15 10:56:17.762163794 +1100 random_images
drwx------.  2 alex alex        6 2022-03-15 10:56:03.539403689 +1100 random_videos
-rw-------.  1 alex alex 11359528 2020-04-22 19:15:52.000000000 +1000 ZoomInstaller.dat
```

So the gap here that needs to be fixed is ensure that new folders when created locally, receive the same modified timestamp as per files get updated with.

**Comment by biokomiker** [comment]
+1 for using lastModifiedDateTime instead of "local" creation date for directories
