### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by csimpi** [abraunegg/onedrive#1927]
### Describe the bug

This package's sylog entries are filling up my entire system drive. 

![image](https://user-images.githubusercontent.com/6192067/163735281-4021db08-b83a-4b2f-960b-20d014ba280d.png)

### Operating System Details

```shell
Linux pop-os 5.13.0-7620-generic
```

### Client Installation Method

From Distribution Package

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

`onedrive v2.4.13-0~202107190106~ubuntu20.04.1`

### What is your OneDrive Application Configuration

```shell
onedrive version                       = v2.4.13-0~202107190106~ubuntu20.04.1
Config path                            = /home/pitt/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/xxxxxxx/yyyyyy-not-public/
Config option 'skip_dir'               = DEV|@Media|Backup
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

### What is your 'curl' version

```shell
curl 7.68.0
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
not public
```

### What are all your local file system partition types

```shell
not public
```

### How do you use 'onedrive'

nothing special here, I just tried to sync my onedrive folder the first time then I didn't touch it. Then this happened, it started to throw hundreds of thousands of records continuously all the time. Even after a reboot. 

### Steps to reproduce the behaviour

I just installed it from distribution, changed the config file (above), and started a sync. 

### Complete Verbose Log Output

```shell
Not relevant, I am sharing the syslog screenshot below
```

### Screenshots

Hundreds of gigabytes EVERY day of these:

![image](https://user-images.githubusercontent.com/6192067/163735281-4021db08-b83a-4b2f-960b-20d014ba280d.png)

You shouldn't report errors like that or should be debounced and throttled.

**Comment by abraunegg** [comment]
@csimpi 
This is your problem: `onedrive v2.4.13-0~202107190106~ubuntu20.04.1`

Please read the installation instructions more carefully. You are using an obsolete and unsupported client version.

**Comment by csimpi** [comment]
@abraunegg 
Thank you.
1. I read it carefully before I installed. Nothing says I shouldn't install from distro, it says it's not recommended
2. Why an officially released version is available if it's a broken package?
3. I don't want to install something from source that I am not sure it won't break and make my files disappear or any other data-loss. 
4. Can I still ask how to stop reporting errors this crazy way?

**Comment by abraunegg** [comment]
@csimpi 
> 1. I read it carefully before I installed. Nothing says I can't install from distro, it says it's not recommended

The instructions advise if your 'distribution version' is not the latest, it is recommended to build from source. This is because your distribution does not keep the package up-to-date. If you have an issue with that - complain to your distribution provider. 

This being said - you have potentially missed reading this: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#important-information-for-all-ubuntu-and-ubuntu-based-distribution-users

![Capture](https://user-images.githubusercontent.com/4956234/163739419-7d36162b-1c63-422e-a971-ffcb73a4e8bc.JPG)

> 2. Why an officially released version is available if it's a broken package?

Because you are using a distribution that does not have an easy way to keep packages maintained. If you have a problem with this - complain to your distribution provider. If you want to fix this, maybe contribute back to your community and become the package maintainer for your distribution.

> 3. I don't want to install something from source that I am not sure it won't break and make my files disappear or any other data-loss, nor install lots of unnecessary dependencies in order to use this.

Installing from source will not cause this sort of effect ... however, as per above .. you should be installing the package from the correct package provider (see answer to point 1 above). If you do not want to do this you need to compile from source or fix your distributions package as per point 2 above.

> 4. Can I still ask how to stop reporting errors this crazy way?

Install the client the correct way, following the correct procedure, taking note of the *known issues* with using packages for Ubuntu based platforms .. or compile from source.

Or do not use a Ubuntu based distribution ....
