### ISSUE TITLE
Can the onedrive application be made usable without root?

### ISSUE THREAD

**Issue by callegar** [abraunegg/onedrive#201]
As is, onedrive requires root permissions to be used.

Apparently, some of the ways in which onedrive can be used (e.g., onedrive running as a system service) do indeed need root.

However, it would be desirable for a simple user to be able to install his own instance of onedrive and run it without root permissions via his command line. Currently this is not possible because onedrive insists on logging on /var/log/onedrive which must be created by root.

It would be nice if onedrive could get from its config dir where to log.

**Comment by abraunegg** [comment]
> As is, onedrive requires root permissions to be used.

This is not an accurate statement at all. The client can be used 100% fine without running as root.

> However, it would be desirable for a simple user to be able to install his own instance of onedrive and run it without root permissions via his command line. 

You can compile the application and leave it in your user directory (without performing `sudo make install` ) and call the binary directly from the directory where you built it.

> Currently this is not possible because onedrive insists on logging on /var/log/onedrive which must be created by root.

Whilst an warning message is generated, it does not prevent the client from running. To fix the permissions - changing the group permissions of `/var/log/onedrive` to `root.users` is the correct approach to resolve - just like any other application, and ensuring that your user is part of the 'users' group. If the application cannot write to this location, the log file is generated in the users home directory.

**Comment by sergiocallegari** [comment]
Please, reopen. I did not notice that the warning on /var/log/onedrive was non-blocking. Still your suggested fix for the warning cannot be applied unless you are root. That is, onedrive cannot provide logs unless (at least for the time needed to create /var/log/onedrive or to change its group ownership) you are root.  This is limitation hits if you are on a machine that is managed by someone else (e.g. a company owned one, a machine in the lab of an academic institution, etc.). Yet, it is a non-structural limitation. Could be relaxed by simply allowing the config file of onedrive to take the log file as an option, so that one can either leave onedrive to its default logging in /var/log/onedrive/%username%.onedrive.log (one file in /var/log/onedrive/ per user) or set it to something in his home (e.g., ~/.local/var/log/onedrive.log).  This is what I was suggesting in my initial bug report.

**Comment by sergiocallegari** [comment]
Or better than reopening, maybe I could open a new bug report with a more up to the point title (e.g. please let the log file of onedrive be configurable).  What is preferable?

**Comment by abraunegg** [comment]
> or set it to something in his home (e.g., ~/.local/var/log/onedrive.log). 

If the client cannot write to `/var/log/onedrive/` , the client already writes the log to the users home.

**Comment by callegar** [comment]
Thanks,
sorry for all the noise, but I am trying to find out if the synchronizer can be used in an academic context and not having enough time for testing causes me to make wrong assumptions (still, this will likely reflect what can happen with users).

Just noticed that I indeed get the log in the home. 

Sorry but I found the "Unable to create /var/log/onedrive/  Please manually create /var/log/onedrive/ and set appropriate permissions to allow write access The client activity log will be located in the users home directory" a bit confusing. An "otherwise" after "write access" might help.

Also it would be nice to be able to silence that message (as users tend to get scared by warnings) and to still make the location of the ondrive.log file in the home configurable (having it at the top may make the home view a bit messy).  For the time being, I see that even without knowing D it is easy for me to keep a local tree with a patched src/log.d hardwired for no message and logging to ".onedrive.log".
