### ISSUE TITLE
Add an option for logfile path

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#212]
**Is your feature request related to a problem? Please describe.**
While we can specify confdir in onedrive command line, the log of different onedrive account will be mixed together as long as you run with same linux user.  And we can't tell clearly which log line is from which instance.

**Describe the solution you'd like**
Add and option for logfile path in config or in the command line.

**Describe alternatives you've considered**
1. Or could you add log tag option in config file?
2. Run it will a different user.
3. redirect console output manually by hand to a file.

**Comment by abraunegg** [comment]
@priv, @AlmightyFloppyFish
Can you please help test this PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/239/head:pr239
git checkout pr239
make
make install
```

This PR provides the following enhancements:
* Change '--download' to '--download-only' to align with '--upload-only' 
* Change the logging to a separate file to not be the default so that excessive disk I/O does not occur (Issue #158)
* Close out Feature Request #108, by only enabling the local logfile when '--enable-logging' is used
* Close out Feature Request #212 by adding a new configuration option to specify the logging directory

To use a different log directory, add the following to `~/.config/onedrive/config`:
```
log_dir = "/path/to/location/"
```
Trailing slash required

**Comment by abraunegg** [comment]
>But I think you need to clearify in readme for whom already expects finding logs in /var/log/onedrive or homedir.

This change in the PR should take care of the changes.

https://github.com/abraunegg/onedrive/pull/239/commits/b8640c4237948a98dee47d85ce4276f50523f619

I plan on making this a 2.2.0 version release, as it is a change in functionality & will be denoting that in the change log / release notes as well

**Comment by abraunegg** [comment]
PR #239 merged
