### ISSUE TITLE
Shared OneNote Directories

### ISSUE THREAD

**Issue by shughesphotons** [abraunegg/onedrive#22]
Hi,

The app works well.

However, I have a small issue. The Shared OneNote directories at the OneNote side returns some strange warnings, e.g.,

"This item type (OneNote Folder Name) is not supported" - since it is shared with others, but has nothing to do with the Ubunto folder being synced. It gives this for every OneNote folder.

Is this a bug and it is ok to just ignore the warning?

Thanks

**Comment by abraunegg** [comment]
Hi,

The syncing of OneNote items is not supported. The OneNote files on OneDrive are not really files, but rather links to get OneNote to load the corresponding Notebook. See https://docs.microsoft.com/en-us/onedrive/developer/rest-api/#working-with-onenote-notebooks for further details.

As we can't sync them this is why the message is displayed rather than erroring out.

Not a bug, not an error - normal application action.

**Comment by abraunegg** [comment]
Added information to FAQ: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions
