### ISSUE TITLE
Handle no connection more gracefully (at least optionally)

### ISSUE THREAD

**Issue by lorenzosu** [abraunegg/onedrive#234]
**Is your feature request related to a problem? Please describe.**
If for some reason the internet connection goes down (cable unplugged, wifi not working, computer goes to sleep), onedrive will quite with `std.net.curl.CurlException@std/net/curl.d(4340): Couldn't resolve host name on handle 55FA79273AF0` and so on, even if launched with the --monitor option. This essentially means that if launched in monitor mode even if the network becomes available again onedrive died.

**Describe the solution you'd like**
Have an option, at least for --monitor, to simply keep trying even if no network was found (obviously warning the user through messages, logs, etc.)

**Describe alternatives you've considered**
having a script which re-starts onedrive indefinitely if it quits, but that's really hacky

**Additional context**
Essentially this would be the same behaviour of other 'cloud sync' clients which remain running even if the connection is absent so that they can start syncing again whenever the network is available again. There are still many situations like mobile, on-the-go, etc. where it's  easy to temporarily lose connection and then get it back.

**Comment by abraunegg** [comment]
@lorenzosu, @lhorace
Whilst I can understand that having an application 'exit' may not be desirable, please can you post the full error log when this occurs so that it can be resolved more gracefully.

However - with this being said, if you are looking for 'onedrive' to constantly be operating in the background regardless of network connectivity to the OneDrive service, you need to use the systemd service files to achieve this.

The service file will restart the application in monitor mode & if the application cannot reach the OneDrive service, will keep restarting the client until it does so.

**Comment by lhorace** [comment]
@abraunegg Actually, I have `systemd-user-unit` `onedrive` enabled and active already. I was astonished for a bit there why this wasn't already implemented in `service-unit-file`, albiet, I didn't have a chance to look at your `unit` file at the time. \o/

**Comment by adudek** [comment]
Hi, you might be interested in running docker container for this purpose. --restart flag brings up onedrive every time it fails. Please refer to https://github.com/abraunegg/onedrive/pull/241 for more info

**Comment by norbusan** [comment]
See https://github.com/abraunegg/onedrive/pull/253 for a fix
