### ISSUE TITLE
Request for Feedback: Sync with Shared Library for OneDrive Business / Office 365

### ISSUE THREAD

**Issue by abraunegg** [abraunegg/onedrive#264]
Hi all,

Please can you respond with the following **IF** you are using the client as per https://github.com/abraunegg/onedrive/blob/master/README.Office365.md to sync a OneDrive Business / Office 365 Shared Library to your local machine.

What I am interested in, is the following:

* Is it working for you
* Account Type (OneDrive Business, Office 365, Office 365 Education etc)
* drive_id format - `b!6H_..._...-..._l7vVxU5` (~66 chars) or `01.....Z` (~34 chars)

I am trying to work out if this is currently working as intended, or is broken for everyone at present.

If you could please respond that would be greatly appreciated to help with planning around this feature and fixing a few issues with how it is implemented.

**Comment by norbusan** [comment]
I have a Office 365 subscription, but I think I am syncing just my own private onedrive space.

Is there a way that I can try out what you need?

**Comment by abraunegg** [comment]
@norbusan 
It's more so if your trying to sync a Shared Library - the feature that was added with PR #206 

Essentially, it seems that for some folk, setting `drive_id` in the config file as per the URL works, but for others it fails (#248) - so really trying to understand - if it is working, what is it working for (account types / libraries etc)

As per #263, I've worked out an easier way to get the 'drive_id' & potentially this would change the entire way the feature PR #206 implemented - but need to understand today how it is being used & where it is being successful.

**Comment by MK-42** [comment]
I'm using o365 business onedrive. I'm syncing a shared personal folder of another user onto my own machine. so far it is working. My drive_id is in the form of `b!gV......`. I patched the #206 to ignore free-space constraints, as the quota reported is zero and no uploads take place instead.
Today I saw a move/rename/reupload bug, but I think thats already fixed. currently updating to HEAD of #206. Will report if it happens again

**Comment by abraunegg** [comment]
@MK-42 
Thanks for the feedback.

**Comment by ndit-dev** [comment]
I'm using Office 365 business. Syncing my private folder works fine.
I'm trying to also sync our sharepoint library from _https://<mycompany>.sharepointe.com/<sharedlibrary>_ 

Following the readme here https://github.com/abraunegg/onedrive/blob/master/README.Office365.md
Gives me this ID in this step

`curl -i 'https://graph.microsoft.com/v1.0/sites/$host,$SiteId,$webId/lists/$listId/drive' -H "Authorization: bearer <your_token>"`
> b!****M**0****X**1****Y**T****T**K****l**k****k**5**_PQ****hS_**YK

When using this in the config file, it **WORKS** for me

in the last step, looking for the root folder, i get this ID

> 01****F**6****V**7****O**4****LRRZ

with this I get the error from #248 
Looks like I used the last ID (the root folder) instead of the actual drive ID when I got the error. So it looks good for me now.

What is the "root folder ID" good for anyway?
Could as well be deprecated from the README.Office365.md

**Comment by abraunegg** [comment]
Closing as solution for obtaining 'drive_id' updated in PR #260
