### ISSUE TITLE
Help detect the need for resync

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#280]
I just shot myself my playing with `skip_dir`, moving files on the OneDrive web site, etc etc. I spare ourselves the details. Anyway, it might be worth auto-detecting the need for `--resync` by 

- saving the last state of `skip` variables into the database
- comparing them (for now string comparison, could be more intelligent)
- warn/error/require --force when differences are found

WDYT?

**Comment by adudek** [comment]
For me most acceptable strategy would be to "preserve all" in dubious situations and create file(confict1,2,3...).ext in case there is no possibility to resolve conflicts. Manual cleanup can be done later more easily than data restoration. Assumption is that we want not to loose anything since we are making effort to store our things in cloud.

**Comment by abraunegg** [comment]
Given all the work regarding configuration checking etc, below are the triggers for needing a resync:
* config file options changed - specifically 'sync_dir', 'skip_file', 'drive_id'
* enabling / reconfigure of 'sync_list' file

We could store in the database at runtime the timestamp of the 'config' & 'sync_list' file and trigger a warning if:
* file is removed
* timestamp changes

If we store the values of 'sync_dir', 'skip_file', 'drive_id' in the database, and the timestamp of 'config' changes, we can then either 'fail fast' citing that a resync is needed, rather than automatically triggering a resync.

If the file is removed, potentially we don't sync as this could cause undesirable local & remote changes from occurring. I would rather 'not' sync in the event of a configuration change that would trigger the need fr a resync than having to sync & deal with conflicts.

Fail fast with an error saying `configuration change detected - please use --resync` or something along those lines

**Comment by norbusan** [comment]
Sounds like a good plan!

**Comment by abraunegg** [comment]
PR https://github.com/abraunegg/onedrive/pull/617 in progress for this enhancement

**Comment by abraunegg** [comment]
PR Testing assistance required:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/617/head:pr617
git checkout pr617
make clean; ./configure; make;
```

**Comment by abraunegg** [comment]
Closing issue as PR #617 implemented
