### ISSUE TITLE
Two account setup

### ISSUE THREAD

**Issue by sfwolfphys** [abraunegg/onedrive#291]
I'm trying to set up two onedrive accounts.  However the documentation is a bit unclear.  What I have done is this:

1. Copied config file over to the `~/.config/od1/config` and `~/.config/od2/config` and changed the `sync_dir` to the desired paths respectively.
2. Ran the `onedrive` command.  I may have added `--synchronize` or not.  I've tried this with the previous fork of the project too, and have had poor success, and I have run the suggested commands as well (with the path to my config files).
```
onedrive --synchronize --monitor --confdir="~/.config/onedrivePersonal" &
onedrive --synchronize --monitor --confdir="~/.config/onedriveWork" &
```
This synchronized everything to the `~/OneDrive` folder, and not my indicated folders.  Then it combined all of my files together.  (Fortunately, untangling them was easy...I don't have a ton of stuff in my personal onedrive folder.)

Should I be getting one sync working before I try the reconfig?  Do I *have* to use the indicated paths to the new config file?

**Comment by abraunegg** [comment]
Hi,

First I would drop `--synchronize` or `--monitor` as you cannot used them together. In your current command like `--monitor` would be used as it takes priority over `--synchronize`. As your trying to get things working, I would test with `--synchronize` and switch to `--monitor` once working.

> This synchronized everything to the ~/OneDrive folder

Unless your config file located `~/.config/onedrivePersonal/config` specified a different value to `sync_dir="~/OneDrive"`  or if the config file was missing in location, the default would have been used

Can you provide the output of the following files:

```
~/.config/onedrivePersonal/config
~/.config/onedriveWork/config
```

Additionally, when testing, use `--verbose` so that you get extra details to help advise if there is an issue.

It also sounds like however you could benefit from #100 to test your configurations before doing an actual sync.

**Comment by abraunegg** [comment]
> Your suggestion for #100 doesn't seem to be working for me:

That's because it is still a feature request and not implemented yet :) It is in progress though as of this morning.

> So if I replace --synchronize with --monitor, I should be set?

It looks that way - should be good to go for you if `--synchronize` is working as you expect it to. I would ensure that it is syncing what is needed by adding `--verbose` as well.

> Also, if I run these lines, with they autosync on login?

Not quite. You have a very 'custom' setup going on, so what you need to do is the following:

1. Create a new service file for each OneDrive configuration file you have
2. Edit that service file to match the configuration you want - ie the confdir option above
3. Enable the modified service file, not the 'onedrive' one, eg:
```
systemctl --user enable onedrive-odECU
systemctl --user start onedrive-odECU
```

**Comment by abraunegg** [comment]
> Proceed with caution here when changing the default sync dir from `~/OneDrive` to `~/MyDirToSync`

Generally when you are changing your `sync_dir` you should run a manual sync & resync:

```
$ onedrive --confdir="/home/swolf/.config/odECU" --synchronize --resync --verbose
$ onedrive --confdir="/home/swolf/.config/odPers" --synchronize --resync --verbose
```

I would then make sure that it is syncing as expected - file additions, removes & so on:

```
$ onedrive --confdir="/home/swolf/.config/odECU" --synchronize --verbose
$ onedrive --confdir="/home/swolf/.config/odPers" --synchronize --verbose
```
Then enable the service files once created & edited for your situation

**Comment by sfwolfphys** [comment]
Ok, so I've never created a service file before, I'm guessing that I would:
1. Copy `onedrive.service` to `onedrive-odECU.service`.
2. Edit the `ExecStart` command to include the proper `--confdir`
3. Repeat for each account/sync location as desired.

Is that correct?

**Comment by sfwolfphys** [comment]
Syncing seems to be working:

```
$ onedrive --confdir="/home/swolf/.config/odPers" --synchronize --resync --verbose
Loading config ...
Using Config Dir: /home/swolf/.config/odPers
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/swolf/odPers
Initializing the Synchronization Engine ...
Account Type: personal
...
```
I'm going to switch to `--monitor`.  Once I get the service running, it seems like it'll work. :)

**Comment by abraunegg** [comment]
> `onedrive --confdir="/home/swolf/.config/odPers" --synchronize --resync --verbose`

You only need to use `--resync` the once - otherwise, what happens is, every sync / application start you are rebuilding the database, meaning you loose the 'state' of what is in sync / non in sync

**Comment by sfwolfphys** [comment]
I made some edits to your README file that would have helped me out.  Use as you see fit:

https://gist.github.com/sfwolfphys/a6dde27b44209cc0ddaf63053569bf6b

**Comment by adudek** [comment]
@sfwolfphys my recommendation for 2-account setup with sync enabled is to use docker image and spawn 2 containers from it. You get "system service" for free with docker deamon.

**Comment by abraunegg** [comment]
> I made some edits to your README file that would have helped me out. Use as you see fit:
> 
> https://gist.github.com/sfwolfphys/a6dde27b44209cc0ddaf63053569bf6b

Thanks - will update the readme as I agree it could me a lot clearer and also contains errors.

**Comment by abraunegg** [comment]
Closing as issue is resolved, will update readme based on feedback
