### ISSUE TITLE
update notifications to handle additional events

### ISSUE THREAD

**Issue by abraunegg** [abraunegg/onedrive#346]
If notification support is compiled in, the following events will trigger a notification within the display manager session:
*   Aborting a sync if .nosync file is found
*   Cannot create remote directory
*   Cannot upload file changes
*   Cannot delete remote file / folder
*   Cannot move remote file / folder

Expand the current coverage for the following events:
* when sync starts and when it concludes
* potentially when starting in monitor loop the number of changes to process

**Comment by norbusan** [comment]
Hi
Concerning start/end of sync operation: this would be very annoying in monitor mode, since it would happen every 45sec (default) and clutter notifications.

Concerning number of changes to process: again, might be cluttering.

I was thinking of if in one sync run (monitor mode) there have been several files up/downloaded (nr of changes?) then report afterwards (uploaded N files, downloaded M files) or similar, but only above a certain treshhold (5?) - otherwise single file edits (vim foobar) will generate too many notifications.

WDYT?

**Comment by abraunegg** [comment]
@norbusan 
I was thinking of somehow leveraging the work in sync.d queryDriveForChanges() to only print a message in monitor mode when starting a new loop if there were remote changes to apply - otherwise be silent.

Certainly could have a 'counter' to report number of 'uploaded' changes if any as well

**Comment by norbusan** [comment]
Wouldn't that query the remote side two times for the set of changes? Maybe *after* the sync just report what has happened?

**Comment by abraunegg** [comment]
@norbusan 
This is what I was thinking:

* The 'monitor' loop in main.d calls performSync()
* Due to the options used for 'monitor', line 657 - sync.applyDifferences(); is called
* This takes us to sync.d line 293 - void applyDifferences()
* This then steps through to line 451 - private void applyDifferences(string driveId, const(char)[] id)

What I was thinking was - before line 580 or around there, 'changes' is an array of changes to process from OneDrive.

What we could do here is - if the array size is >0 or something else (greater than 5 changes .. a configurable value in the config file??), send a notification.

This way - there is no double call, and re-using the calls already made to detail / notify how many changes are being processed at this time.

Thoughts?

**Comment by norbusan** [comment]
Sounds good, please see branch norbert/notif2 which does that, default with 5 changes, can be configured with `min_changes_for_notification` configuration option. (No docs by now).

Questions:
- is that enough?
- better name for config value
- how to deal with misconfiguration and non-integers in the config file
- changes is not the number of files downloaded in fact - I add 6 files via the web interface, and 7 changes were reported.

**Comment by abraunegg** [comment]
@norbusan 
Will review further when I have some time next week - quickly looked over the branch and looks OK.

>changes is not the number of files downloaded in fact - I add 6 files via the web interface, and 7 changes were reported.

Yes - this is due to the 'root' change - a root change exists whenever there is a file / folder change as well - as the deltaLink gets updated.

**Comment by norbusan** [comment]
@abraunegg should I open a PR for that, or do you look into it separately? Thanks for the explanation, maybe we reduce the *displayed* number by one to account for that?

**Comment by coxackie** [comment]
This is great - many thanks. I think the direction you are taking makes total sense. Looking forward to testing it.

 In terms of clutter, I do not know what your thoughts are in terms of timeout of notifications. Pop-up temporary (1-3 sec) notifications for local to cloud changes should be ok, since it most probably involves someone working on the files on the spot in front of the screen. For cloud to local sync, maybe some permanent (until clicked) notification for large changes would be preferable. These are just personal views, based only on my user case.

**Comment by norbusan** [comment]
@coxackie I disagree that every local change should trigger a notification. A simple `vim foobar.txt` would trigger around 4 or more notifications, not to speak of editing and saving.

Also, the length of the popup and whether it is automatically dismissed cannot be controlled (as far as I remember), but is normally configurable in the desktop environment.

**Comment by coxackie** [comment]
@norbusan As I mentioned, these are only personal views - at the end of the day, you are the devs and will make the decisions. That being said, since there is a `min_changes_for_notification` config option, very frequent pop ups could be avoided.
As far as I can see, the API of `libnotify` allows for setting the timeout, but again I am not sure whether different DEs react differently to it. (In GNOME it should be fine.)

**Comment by abraunegg** [comment]
Closing as PR #355 merged
