### ISSUE TITLE
Setting up multiple accounts

### ISSUE THREAD

**Issue by vtoufex** [abraunegg/onedrive#352]
Hello, your solution works perfect on Fedora 29. I still haven't figured out how to authorize the second account you state that the application supports. And then bind the 2nd account to the instance of onedrive pointing to the different config file. Thanx in advance

**Comment by abraunegg** [comment]
This is listed in the readme file:
https://github.com/abraunegg/onedrive/blob/master/README.md#using-multiple-onedrive-accounts

What you need to do is this:
1. Create 2 different 'config' directories under ~/.config/ for example:
```
~/.config/onedrive-account-1
~/.config/onedrive-account-2
```
2. Create 2 different 'sync' directories under your home drive, for example:
```
~/OneDrive-Account-1
~/OneDrive-Account-2
```
3. In each of the 'config' directories copy the 'default' config file
4. Edit each of the 'config' files so that:

~/.config/onedrive-account-1/config:
```
sync_dir = "~/OneDrive-Account-1"
```
~/.config/onedrive-account-2/config:
```
sync_dir = "~/OneDrive-Account-2"
```

5. Run the client specifying the configuration directory:
```
onedrive --confdir '~/.config/onedrive-account-1' --synchronize --verbose
onedrive --confdir '~/.config/onedrive-account-2' --synchronize --verbose
```

What should happen is that OneDrive Account 1 data will be saved in ~/OneDrive-Account-1 and OneDrive Account 2 data will be saved in ~/OneDrive-Account-2


If you want to then run these as service accounts refer to:

https://github.com/abraunegg/onedrive/blob/master/README.md#automatic-syncing-of-both-onedrive-accounts

**Comment by abraunegg** [comment]
That would be this:
```
onedrive --confdir '~/.config/onedrive-account-1' --synchronize --verbose
onedrive --confdir '~/.config/onedrive-account-2' --synchronize --verbose
```

The first line, you will get prompted to authorised via a URL & provide a response

Likewise for the second line.

Authorise each URL with the right account and provide the correct response

**Comment by vtoufex** [comment]
Thanx again. It didn't catch my eye that it could be done this way. Already authorized the first account and tried some stuff to get the hang of it. 😎

**Comment by abraunegg** [comment]
Closing case as answer provided
