### ISSUE TITLE
Synchronization fails for empty files

### ISSUE THREAD

**Issue by jose-sanchezm** [abraunegg/onedrive#37]
Hello, while trying to debug issue #35 I've found that uploading fails for empty files with the following error:

```
Uploading file <empty_file> ...
Uploading fragment: 0-0/0
OneDrive returned a 'HTTP 400 - Bad Request' - gracefully handling error
 done.
std.json.JSONException@std/json.d(494): Key not found: size
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, const(char[])) [0xdeb23637]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xdebc7c66]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0xdeb78275]
??:? void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0xdeb4a73e]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xdeb49abb]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xdeb499b2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xdeb499b2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xdeb499b2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xdeb499b2]
??:? void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xdeb499b2]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xdeb48b81]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0xdeb2f5a7]
??:? _Dmain [0xdeb2ef47]

```

**Comment by abraunegg** [comment]
Uploading 0 byte files actually works - but only when using `simpleFileUpload` - refer to https://github.com/OneDrive/onedrive-api-docs/issues/53

I think whats happening in your case, in #2 (which I asked you to test), this forces all uploads for Business to be sessions so that the lastModifiedTime get's included as part of the upload to prevent a double hit on the file. The `simpleFileUpload` function has no way to set the timestamp, thus has a double hit creating a new file version.

What needs to happen is some logic that where a file is 0 byte in size, use `simpleFileUpload` regardless of account type. Will fix this in #2 branch as it is a regression there.

**Comment by abraunegg** [comment]
Posted this commit https://github.com/abraunegg/onedrive/commit/9ec5885fa058e88ae5cfbc0def1d8cb066e4c4a5 to resolve this issue against https://github.com/abraunegg/onedrive/tree/Issue-%232

Can you help validate that brach for this issue (as this issue does not occur with master)

**Comment by jose-sanchezm** [comment]
I confirm that now I can upload 0 byte files. Thank you.
