### ISSUE TITLE
Error on resync operation

### ISSUE THREAD

**Issue by djdejawu** [abraunegg/onedrive#372]
Giving up on sync after three attempts: Key not found: id
std.json.JSONException@std/json.d(540): Key not found: id
----------------
/root/dlang/dmd-2.084.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x598c0b]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x648fb6]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x5fc881]
src/sync.d:81 itemdb.Item sync.makeItem(ref const(std.json.JSONValue)) [0x5cb580]
src/sync.d:1822 void sync.SyncEngine.saveItem(std.json.JSONValue) [0x5d35cd]
src/sync.d:1704 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5d2ab2]
src/sync.d:1376 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d11b4]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1368 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5d10ab]
src/sync.d:1049 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5cfc05]
src/main.d:646 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x5aac39]
src/main.d:482 _Dmain [0x5aa2c1]

**Comment by abraunegg** [comment]
@djdejawu 
Please can you update your bug report properly by following: https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues

**Comment by abraunegg** [comment]
@djdejawu 
Please can you respond

**Comment by abraunegg** [comment]
@djdejawu 
Please can you respond

**Comment by abraunegg** [comment]
Closing case due to lack of response from @djdejawu 

In looking at the error submitted, also the output does not align to the code in current 'master' so can only assume here without any further details that @djdejawu is using an older version of the client.

The error `Key not found: id` sounds familiar to #325 which was fixed by https://github.com/abraunegg/onedrive/commit/ddc5d602da94199a8dc5d8ab991b7d631ff5d4a4#diff-a601932e4174e1bb743e6ea51f804d01 

Without @djdejawu responding it is hard to confirm otherwise.

**Comment by djdejawu** [comment]
WTF??? Are you normal???

**Comment by djdejawu** [comment]
# onedrive --version
onedrive v2.2.5-6-g61c40c6

**Comment by abraunegg** [comment]
@djdejawu 
You opened an issue case without providing *any* context - very important details to assist with the issue. All requests to you to provide that additional information was ignored. I gave you 96 hours to respond which is more than enough time to account for timezone differences, travel & whatever.

You now have provided 'some' context in the application version you are running which helps a little.

If you were running the latest codebase, your version string would be `v2.2.5-25-gb15948e`

So - again, as per [how to report issues](https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues) refer to point 1 which states:

Check the version of the application you are using `onedrive --version` and ensure that you are running either the latest release or built from master.

If the issue still persists the onus is on you to provide as much detail & context to assist with tracking down the issue & reporting an issue in the correct manner with *all* the details requested in the issue template. This then helps 2 ways:

1. Helps create an environment locally where the issue can be replicated & fixed much more easily
2. If it cannot be replicated locally, enough information exists that a patch can be created by which you have to test and confirm that it is working and is fixed. 

Fixing an issue is a two way street - you cannot simply fire off an error message and provide no additional details & not respond & then expect it to be magically fixed with zero communication.
