### ISSUE TITLE
401 unauthorized if manual sync yet systemctl runs on

### ISSUE THREAD

**Issue by webe3** [abraunegg/onedrive#395]
I am running version 2.2.5-1 as from the Debian repository.  Everything seemed to be fine.  I noticed that a file that had been created elsewhere on onedrive did not copy over.  I checked onedrive status using "systemctl --user status onedrive"  and it shows as running with no issues.
```
$ systemctl --user status onedrive
\u25cf onedrive.service - OneDrive Free Client
   Loaded: loaded (/usr/lib/systemd/user/onedrive.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-03-01 07:53:08 CST; 2ms ago
     Docs: https://github.com/abraunegg/onedrive
 Main PID: 3515 (onedrive)
   CGroup: /user.slice/user-1000.slice/user@1000.service/onedrive.service
           \u2514\u25003515 /usr/bin/onedrive --monitor
```

However, if I try to manuall synchronize, I get a 401 error and a Segmentation fault:
```
$ onedrive --synchronize
Initializing the Synchronization Engine ...

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid

Segmentation fault
```
I corrected the problem by stopping the systemctl onedrive then manually removing the file "refresh_token" in .config/onedrive and then onedrive --synchronize.  I was prompted to authorize again which I did and then the sync worked as expected.  I suspect that the authorization became invalid due to a required password change on the windows system.  However, I have the following issues:

1. There is nowhere in the documentation that I can find that says you have to reauthorize after a password change.
2. Why does the systemctl daemon happily display an okay status even though no synchronization is happening?
3. Is there anywhere in the documentation showing the proper way to reauthorize the application?  Are the steps I did correct?
4. What is the proper way to enable logging when using systemd?

**Comment by abraunegg** [comment]
@webe3 
Many thanks for your detailed feedback - greatly appreciated.

> 1. There is nowhere in the documentation that I can find that says you have to reauthorize after a password change.

Agreed. This is lacking in the documentation, and will fix this morning.

> 2. Why does the systemctl daemon happily display an okay status even though no synchronization is happening?

This is because systemctl will constantly "restart" the application when it exits due to the error. So to systemctl, because it has restarted the application, everything is OK.

To check what the application is "actually" doing, use the following command:

```
journalctl --user-unit onedrive -f
```

You should be able to check & see what the application logs are telling you regarding sync status and process. I suggest to rely on that rather than 'is the service running' or a combination of both to determine actual status.

> 3. Is there anywhere in the documentation showing the proper way to reauthorize the application?  Are the steps I did correct?

Again this is lacking in the documentation and will fix. Essentially the process you should have used:
```
systemctl --user stop onedrive
onedrive --logout
systemctl --user start onedrive
```
The `onedrive --logout` logs you out & requests for re-auth as one step.

> 4. What is the proper way to enable logging when using systemd?

By default, logging is kept to a minimum to avoid excessive disk I/O. You can check the default application logging via:
```
journalctl --user-unit onedrive -f
```
If this is 'too light' for you, I would suggest for you to manually edit your onedrive service file and add `--verbose` to the parameters. This will give you a much richer level of logging.

**Comment by abraunegg** [comment]
Closing case as PR #396 is merged
