### ISSUE TITLE
Do not delete all files, if device is not mounted

### ISSUE THREAD

**Issue by rednag** [abraunegg/onedrive#514]
**Is your feature request related to a problem? Please describe.**
Sometimes I unmount my SD card and then the onedrive service is deleting all my files from the cloud, then I've to recover a lot of data which sucks because it needs a lot of time.

**Describe the solution you'd like**
If the path, which is onedrive is monitoring is not available, it should stop until it is available.

**Describe alternatives you've considered**
Pause the service with a failure code.

**Additional context**
I really like the onedrive service from you, I'd like to see an improvement in handling a unexpected situations.

**Comment by abraunegg** [comment]
@rednag
Whilst this not good - there is no way to differenciate between you doing:
* intentional rm -rf *
* unmount
* other

This is not a bug, will not fix

Suggest that you:
* dont use monitor mode for your complex setup
* implement scripting to sync
* implement your own validation when your mount is mounted / not mounted before sync

**Comment by rednag** [comment]
It is a feature request not a bug!

I think it is not really hard to detect, if the path is available or not!

**Comment by abraunegg** [comment]
No - the same 'is there' / 'is available' / 'is mounted' check ONCE  running in monitor mode is the same as doing an rm -rf

Patches welcome if you think you can fix, otherwise dont rely on monitor mode for your complex setup
