### ISSUE TITLE
Shared folders syncing

### ISSUE THREAD

**Issue by ukreddy-erwin** [abraunegg/onedrive#535]
How to sync shared folders, in the app.

104 and 5, issues looks similar to this but no command line options there.

My task is to sync a shared folder and create a sub folder inside it and upload my artifact there.

Any suggestion?

**Comment by abraunegg** [comment]
@ukreddy-erwin 
Please can you read all the documents here: https://github.com/abraunegg/onedrive/tree/master/docs

Also - there is a reason why there is a 'Bug Report Template' - please use this when submitting an issue or request. This helps us understand what is going on:

--------------------------
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
A clear and concise description of what the bug is.

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Application configuration: Output of `onedrive --display-config`
*   Curl Version: Output of `curl --version`

**Note:** If curl version is >= 7.62.0 please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Once the full debug log has been generated & emailed, please retry your sync by adding `--force-http-1.1`. If this is successful, please advise in issue ticket that `--force-http-1.1` was successful in resolving your issue.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output
--------------------------


For example - my questions are:

* Issue 5 - OneDrive Office 365 Shared Folders ... however you don't indicate what account type your using
* Issue 104 - Details Quota support and issues around reporting how much space


Without knowing anything else - syncing a shared folder is a straight forward process. You configure the client, create the directory locally, but the artifact in that local directory and sync. There is nothing else special to perform.

**Comment by abraunegg** [comment]
Closing issue as question answered

**Comment by ukreddy-erwin** [comment]
I have gone through usage.md
https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md
Here you mentioned as :
go to the Shared files list, right click on the folder you want to sync and then click on "Add to my OneDrive"

But that option doesn't exist in the onedrive.

![image](https://user-images.githubusercontent.com/21240709/59595061-ac707200-9112-11e9-8b3f-a1b3bc0610e0.png)
 Any other option?

**Comment by abraunegg** [comment]
First question:

* What is your OneDrive account type?

Shared folders as per the readme is only applicable for OneDrive Personal account types.

OneDrive Business / Office365 Shared Folders is not supported - however is a work in progress (see #459 and #473 for details)

**Comment by abraunegg** [comment]
Closing issue as question answered and docs updated with clarification on shared folder support
