### ISSUE TITLE
where is a default config?

### ISSUE THREAD

**Issue by karl-ruhigen** [abraunegg/onedrive#54]
I've successfully installed and run the `onedrive` on linux.

Default `~\OneDrive` folder is syncronizing well.

But I can't set the sync dir to my preferred folder (`~\library`).

Editig the file `~\onedrive\config` have no effect

Runnig `onedrive -confdir "~\onedrive"` doesn't create the new config file.

**Question:**

How to set the sync dir to `~\library` ?

**Comment by yn-coder** [comment]
Same problem.

I've manually copy the `config` file from `~\onedrive` to `~\.config\onedrive` (this is a default place) - now working well.

**Comment by abraunegg** [comment]
@karl-ruhigen, @yn-coder 

The config file for the application resides in `~/.config/onedrive/` as a file called `config`

This file does not get created by default, unless you want to change the 'default' operational parameters. The current readme is kind of 'out-of-date' in that respect as there is not even a 'default' config file in the source tree to copy over.

**Please Note:**
Proceed with caution here by changing the default sync dir from ~/OneDrive to ~/library

The issue here is around how the client was originally coded & how the relative paths are stored in the database. If the config file is missing, or you don't use the sync_dir parameter - what will happen is the client will 'think' that either all your data has been deleted - thus delete the content on OneDrive, or will start downloading all data from OneDrive into the default location.

Now - with this being said:

To make your own configuration file to override the defaults: 
```
vi ~/.config/onedrive/config
```
File contents:
```
sync_dir="~\library"
```

This should get you going in terms of setting the configuration for different sync location - however in testing this - it appears that it is not working as it should be, so looks like this is a bug when using the config file for the sync_dir option & when passing in the --syncdir from the command line.

Thanks for bringing this to my attention.

**Comment by abraunegg** [comment]
Can you please test the following:

https://github.com/abraunegg/onedrive/pull/55

```
git clone https://github.com/abraunegg/onedrive.git
git fetch origin pull/55/head:pr55
git checkout pr55
make
make install
```

In testing here locally:

```
Loading config ...
Using Config Dir: /root/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/library
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1099372677600
Fetching details for OneDrive Root
OneDrive Root exists in the database
Applying changes of Path ID: <redacted>
Uploading differences of .
Processing root
The directory has not changed
Processing asdf.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
```

**Comment by yn-coder** [comment]
I'll try to test it.

About config - I think you need to write it in docs. Thank you.

**Comment by abraunegg** [comment]
Updated the readme file to clarify usage, warning and provide examples.

**Comment by abraunegg** [comment]
@karl-ruhigen, @yn-coder 
Any update in testing the fix for resolution to your issue?

**Comment by abraunegg** [comment]
Closing this issue as validated externally, code change synced to master.
