### ISSUE TITLE
Consider renaming this project

### ISSUE THREAD

**Issue by thomasfedb** [abraunegg/onedrive#542]
It might be helpful to rename this project to something other than the name of the service it interacts with. This would also help people tell this project apart from @skillion's project, now that this project has diverged significantly.

**Comment by abraunegg** [comment]
> now that this project has diverged significantly.

I disagree that this project has diverged significantly. Bug fixes and greatly enhanced yes - re-written, different language / compiler - no. It will remain named 'as is' for the time being.

**Comment by thomasfedb** [comment]
Well, it's certainly an impressive diff!
https://github.com/skilion/onedrive/compare/master...abraunegg:master?expand=1#files_bucket

**Comment by abraunegg** [comment]
yes - lots of work by myself, @norbusan & others who have contributed. Given that these pulls:
* https://github.com/skilion/onedrive/pull/82
* https://github.com/skilion/onedrive/pull/314

were never responded to or even acknowledged by @skilion - as per many of the issues / other PR requests submitted by others, this is why I started the fork to maintain & ensure this application works, is a bug / issue free as possible and is a usable tool for those who need it.

**Comment by abraunegg** [comment]
@thomasfedb 
Also - I am really interested in your comment here: https://bugzilla.redhat.com/show_bug.cgi?id=1692994

> I currently use onedrive 1.1.1 on F29 without issue, but version 2.x.x would break my configuration.

Given that the Skilion code base is broken in v1.1.1 with API changes (and even v1.1.3 has issues) - what exactly would "break" your configuration? I am curious to know.

Given our discussion on this matter earlier when suggestion to change to a more active upstream (https://bugzilla.redhat.com/show_bug.cgi?id=1598934) - you had issues that I was (at the time) still using v1.1.3 naming conventions - and that moving to a v2.x release was more applicable which satisfied your request over the introduction of `--synchronize` as a switch to actually sync (rather than the default of v1.1.x syncing blindly and potentially causing issue) .... so what in the v2.x.x codebase would 'break' your configuration?

**Comment by thomasfedb** [comment]
Hey @abraunegg, not sure those comments are relevant to this discussion.

Regardless, you provide a good example of the breaking changes between 1.1.x and 2.x.x yourself, i.e. the introduction of a `--synchronize` flag. I'm currently using 2.3.2 on my new system.

**Comment by abraunegg** [comment]
@thomasfedb 
>not sure those comments are relevant to this discussion

IMHO it's entirely relevant to this discussion - as your advocating changing the name to 'onedrive2' in the Bugzilla  for packaging purposes - which would then put the 'source' at naming odds to Fedora packaging name .. hence then comes a request to change the name of the project ... 

> I'm currently using 2.3.2 on my new system.

I wouldn't use that version ... significant bugs and fixes post that version already. Current release version is recommended if wanting a stable codebase rather than 'master'.

**Comment by thomasfedb** [comment]
@abraunegg it's very common to add a major version number to a package when there are breaking changes (although very useful changes) that you want users to explicitly choose to use. In any case, F29 will be EOL in 6 months and I think we're unlikely to take that step anyway.

My suggestion to rename the project is unrelated to that discussion. I think it would make it easier for people to find this project if it had a unique name, that's all. Google still puts skillion's fork top for "github onedrive" for example.

At the moment 2.3.2 is the latest version in the Fedora repos, hence what I'm using. I'm sure we'll package 2.3.4 in due course.

**Comment by thomasfedb** [comment]
In fact 2.3.4 is currently in our testing repos, so it won't be long at all!

**Comment by abraunegg** [comment]
@thomasfedb 
No problem - sounds great

**Comment by norbusan** [comment]
@abraunegg indeed, the skillion client is much more visible, despite the fact that it is broken. Such a shame.

**Comment by abraunegg** [comment]
@norbusan 
Agreed .. it is a shame the original author is AWOL and not much else can be done other than help those that get pointed to the incorrect version
