### ISSUE TITLE
Are files written in capital the same as non-capital within onedrive?

### ISSUE THREAD

**Issue by mwgrient** [abraunegg/onedrive#685]
Hi reader,
My feature request is problem related: for example;
For OneDrive .xinitrc is the same as .XINITRC, and when both are existing:

$ `onedrive --synchronize --confdir ~/.config/onedrive/Private/`

> Initializing the Synchronization Engine ...
> Syncing changes from OneDrive ...
> ERROR: A local file has the same name as another local file.
> ERROR: To resolve, rename this local file: /home/mwvandergrient/OneDrive-Private/./DOT-files/.XINITRC
> Skipping uploading this new file: /home/mwvandergrient/OneDrive-Private/./DOT-files/.XINITRC
> $ 

My feature request: allow capital and non-capital and see them as two different files.
Regards, Marco.

**Comment by abraunegg** [comment]
@mwgrient 
This is not possible. As per the following link:

https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#local-file-and-folder-naming-conventions

The files and directories in the synchronization directory must follow the Windows naming conventions. The application will attempt to handle instances where you have two files with the same names but with different capitalization. Where there is a namespace clash, the file name which clashes will not be synced. This is expected behavior and won't be fixed.

Windows naming conventions: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

**Comment by abraunegg** [comment]
Closing issue as question answered as this is a Microsoft OneDrive limitation.
