### ISSUE TITLE
Synchronize a single file

### ISSUE THREAD

**Issue by debugbb** [abraunegg/onedrive#697]
The selective synchronization folder in the existing function is very useful. It is recommended to increase the API for synchronizing individual files. Thank you.

**Comment by abraunegg** [comment]
@debugbb 
Hi - Please can you try and be a little bit more descriptive with what your wanting to do.  [Selective Sync](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#selective-sync-via-sync_list-file) today supports files & folders.

If English is not your native language - please write in your native language and be as verbose as possible as I will use Google Translate to assist.

**Comment by debugbb** [comment]
因为我的onedrive某个文件夹下有很多文件，所以想单独同步一个指定的文件，请问现在可以支持吗？阅读了使用说明（usage），并没有找到方法，谢谢！

**Comment by abraunegg** [comment]
**Translation:**
Because my onedrive has a lot of files under a certain folder, I want to synchronize a specific file separately. Can I support it now? Read the usage instructions (usage), and did not find a way, thank you!

There are 2 ways to achieve this:

**Option 1: Utilise multiple configurations**
```
onedrive --synchronize --verbose --confdir="~/.config/onedriveAllFileConfigl" &
onedrive --synchronize --verbose --confdir="~/.config/onedriveSingleFile" &
```
In this scenario, in the `~/.config/onedriveSingleFile` directory, you would have a `sync_list` file that ONLY contains the file you want to sync, nothing else. 

Test each option with `--dry-run` to confirm operation. 

**Option 2: Use / Modify sync_list file**
In this scenario, you would modify `sync_list` each time with the file you want to sync. For each sync, you would test with `--dry-run` then sync, including the `--resync` option as you are changing sync directives.

**Comment by debugbb** [comment]
你说的我没看明白，可能是我没表述明白我的意思，我是想单独下载一个文件

**Comment by abraunegg** [comment]
Translation:
I didn't understand what you said. Maybe I didn't express my meaning. I want to download a file separately.

It is the same process - configure `sync_list`. If you just wish to download the file, utilise also the `--download-only` directive.

**Comment by debugbb** [comment]
已经解决了，就是用这个办法，感谢

**Comment by abraunegg** [comment]
**Translation:**
Has been solved, is to use this method, thanks
