### ISSUE TITLE
Executing program through proxy

### ISSUE THREAD

**Issue by Wanghley** [abraunegg/onedrive#698]
I was trying to use the onedrive client in Linux Lite at the university, but there is a proxy right there... so the app didn't work with `onedrive --synchronize` and I was frustated. I tried to search about this in the internet but there was nothing about it.

The app doesn't support connection through in linux, even if the proxy is set. So it could be added to the application, since there are a lot of  places that we use computers through proxy.

I tried to set the proxy manually in the entire system, but the `onedrive --synchronize` or the `onedrive --monitor` didn't work again. Because of this I'm requesting a new function in the client. An function `--proxy` for example.

Since now, thank you very much for your time!

**Comment by abraunegg** [comment]
@Wanghley 
Proxy support is indeed supported as per the usage documentation: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#access-onedrive-service-through-a-proxy

Essentially you need to set the following for the user:
```
HTTP_PROXY=http://IP:PORT
HTTPS_PROXY=http://IP:PORT
```
so that this is visible for the user when you perform an `export`:
```
declare -x HOME="/home/alex"
declare -x HOSTNAME="centos7full"
declare -x HTTPS_PROXY="http://IP:PORT"
declare -x HTTP_PROXY="http://IP:PORT"
declare -x LANG="en_AU.UTF-8"
```

When this is correctly configured and looking at the proxy server logs, traffic now flows through the configured proxy server:
```
1571771208.108    394 192.168.123.234 TCP_TUNNEL/200 5663 CONNECT login.microsoftonline.com:443 - HIER_DIRECT/40.126.14.161 -
1571771213.364   5252 192.168.123.234 TCP_TUNNEL/200 2596 CONNECT login.microsoftonline.com:443 - HIER_DIRECT/40.126.14.161 -
1571771213.365   4622 192.168.123.234 TCP_TUNNEL/200 14537 CONNECT graph.microsoft.com:443 - HIER_DIRECT/20.190.142.178 -
```

If your proxy server requires authentication, you need to configure your environment as follows:
```
export HTTP_PROXY=http://user:password@your-proxy-ip-address:port/
export HTTPS_PROXY=https://user:password@your-proxy-ip-address:port/
```

**Comment by abraunegg** [comment]
@Wanghley 
Closing case as question answered & details showing how to use a proxy server have been provided.
