### ISSUE TITLE
Ability to sync to remote folders on OneDrive

### ISSUE THREAD

**Issue by liam-456** [abraunegg/onedrive#777]
Is there a way to be able to 'one-way' upload sync the onedrive directory (on local machine) to a subfolder in my onedrive? I see a potential reference here in one of the example dry run outputs in the USAGE.md, but no other documentation. Any help would be much appreciated!

> OneDrive Client requested to create remote path: ./newdir
The requested directory to create was not found on OneDrive - creating remote directory: ./newdir
Successfully created the remote directory ./newdir on OneDrive
Uploading new file ./newdir/newfile.txt ... done.

**Comment by abraunegg** [comment]
@liam-456 
> Is there a way to be able to 'one-way' upload sync the onedrive directory (on local machine) to a subfolder in my onedrive?

There is a way by using the `--single-directory` directive.

On your local system, you would have the configuration file for sync_dir as `~/OneDrive`

Inside this folder, you would then have another folder (for example: `Upload_from_Local`)

Inside this local folder, this is where you would store all your OneDrive files / data that you wish to sync.

From the CLI, you then could utilise the following command for example:

```
onedrive --synchronize --upload-only --single-directory 'Upload_from_Local'
```

This would have the net effect of:
* Upload only the local folder 'Upload_from_Local'
* Store all that data in OneDrive online under this folder 'Upload_from_Local'

An real world usage example of this, is this is exactly how I utilise the client for [MyNAS Storage Appliance](http://www.mynas.com.au/) which I have also developed - allowing multiple systems to replicate to the same OneDrive account. The folder name used however is the UUID of the platform, so that you can differentiate which system uploaded what data. If you review the 'Administration Guide' on page 177 you can see an example of the resulting online view when using this method.

**Comment by liam-456** [comment]
Of course! I just didn't think of it that way, really....

Thank you!
