### ISSUE TITLE
[Question] - Local sync dualboot

### ISSUE THREAD

**Issue by Davincible** [abraunegg/onedrive#782]
I have a windows/linux dual boot with all my documents backed-up to OneDrive, yet still want them all available offline. So, I have a partition with my "OneDrive" folder where keep my complete onedrive directory. 

The windows client however downloads al files as symbolic links, not as the files themselves, even when "keep offline" is checked. Is it possible for both this linux client as well as the official client to interact with the same local files? So that I always have a local copy of all my files, just backedup to the cloud?

**Comment by abraunegg** [comment]
@Davincible 
> I have a windows/linux dual boot with all my documents backed-up to OneDrive, yet still want them all available offline. So, I have a partition with my "OneDrive" folder where keep my complete onedrive directory.
> 
> The windows client however downloads all files as symbolic links, not as the files themselves, even when "keep offline" is checked. 

I think what you are asking about here is 'on-demand' files - see https://github.com/abraunegg/onedrive/issues/757

> Is it possible for both this linux client as well as the official client to interact with the same local files? So that I always have a local copy of all my files, just backedup to the cloud?

This client will download all files as configured (read the documentation to configure things to skip certain files / directories / inclusion / exclusion etc), so that you have a full copy of the file or data on your local file system.

**Comment by abraunegg** [comment]
@Davincible 
Closing as question answered
