### ISSUE TITLE
Daemon - Failed to add match 'onedrive'

### ISSUE THREAD

**Issue by pluniak** [abraunegg/onedrive#794]
Hi,

I'm using your solution on Ubuntu for my private and my work account of onedrive. I built it as outlined in your docs. Everything is running well except for the daemon. After running these two commands,

systemctl --user enable onedrive
systemctl --user start onedrive

checking the logs gives me this fault:
Failed to add match 'onedrive': Das Argument ist ungültig

This is German and means that the argument is not valid. No syncing is happening.

Any help will be greatly appreciated as I have no clue how to fix this.

Thanks,
Philipp

**Comment by norbusan** [comment]
I guess that the following happens:
By default, `onedrive` tries to log to `/var/log/onedrive`. If this directory is not available or writable by the user, it will fail.

Can you try starting OneDrive by hand: `onedrive --monitor`? What is the output?

**Comment by abraunegg** [comment]
@pluniak 
Can you provide some log line examples as to exactly what you are seeing - something like the last 10-20 log lines  for the service?

Can you also provide the entire output of your onedrive systemd service file as installed?

@norbusan is correct that the application attempts to write to /var/log/onedrive - however only if `--enable-logging` is present, otherwise this is not performed. Quite a while ago this was removed as a default from the systemd files - so I am wondering if it is still present in yours.

This being said, this should not 'stop' the application from starting - as if it cannot write to that location it defaults to the home directory.

> 'Das Argument ist ungültig'

My 'best' guess here is that something in your systemd service file is not correct - leading me to the following assumptions:

1. You have the 'skilion' version somewhere on your system - and it does not like the options the systemd service files are trying to use.
2. You have edited the systemd service file and added / modified the command parameters with something that is not valid.

As you have not also provided all the required details when opening an issue as per https://github.com/abraunegg/onedrive/#reporting-issues please can you also update your first post with all of the details as required as per https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md

The issue templates exist so that information can be provided to help quickly isolate what is going on.

**Comment by pluniak** [comment]
@abraunegg @norbusan 
Thanks for coming back to me so quickly.

I solved the issue meanwhile. If I had red the ReadMe all the way to the end, I would have seen that one needs to set up a daemon per onedrive account (which makes sense, of course). Sorry for wasting your time.

Setting up the daemon per account was a bit tricky, however, because it was not clear from the docs to me that the unit files (e.g. onedrive-work.service) need to be located in /usr/lib/systemd/user. This is probably clear for Linux experts, but not for me.

Kind regards,
Philipp

**Comment by abraunegg** [comment]
@pluniak 
PR requests to update / clarify documentation is always welcome

**Comment by pluniak** [comment]
@abraunegg 
Done
