### ISSUE TITLE
Haven't upload to Ubuntu package repository?

### ISSUE THREAD

**Issue by linchangyi** [abraunegg/onedrive#801]
> Ubuntu, available from the package repository as [onedrive](https://packages.ubuntu.com/search?keywords=onedrive&searchon=names&suite=all&section=all)

In  your install guide,  saying that there is an available package in ubuntu repository,  but when I checked it ,   found out that it is the original skilion onedrive.

**Comment by abraunegg** [comment]
@linchangyi 

This is because there is no clear mechanism for adding a package to the Ubuntu [<release>-updates] repository.

With other distributions, when I release a new version, package maintainers push that to their 'updates' repositories, so that users get the latest version of the package next time they perform a system update.

I have even sought advice from ubuntu-release@lists.ubuntu.com however zero response from the members on that mailing list.

If you know how to do this, please, by all means, become the maintainer of the Ubuntu package and ensure that it is kept up to date.

So for Ubuntu - as per the advice - if the package is older, speak to the maintainer - otherwise you HAVE to build from source.

**Comment by abraunegg** [comment]
Closing issue as question answered
