### ISSUE TITLE
Changing sync directory doesn't work

### ISSUE THREAD

**Issue by Photonico** [abraunegg/onedrive#837]
I have modified the configuration file`~/.config/onedrive/config`:
```
sync_dir="/home/lu/Onedrive/"
```
And show the config with `onedrive --display-config`:
```
onedrive version                    = v2.3.13
Config path                         = /home/lu/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/lu/Onedrive/
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

however, when I resync with `onedrive --resync`:
`sudo onedrive --resync --synchronize`
The dir is also `/root/OneDrive/`

How to change the sync dir correctly?

**Comment by abraunegg** [comment]
@Photonico 
The issue here is that you are running the application via sudo:
```
sudo onedrive --resync --synchronize
```

sudo is elevating your user to 'root', thus using 'root' permissions & a default configuration for 'root' - thus runs as root.

If you are trying to run the application as your 'lu' user, try without sudo

Please also, in future follow the directions for raising an issue - https://github.com/abraunegg/onedrive#reporting-issues - as you are missing information that would help in this situation - such as the debug log file which would show exactly how and why this is occurring.

**Comment by abraunegg** [comment]
Closing issue as question answered
