### ISSUE TITLE
Feature request: mount OneDrive directory as FUSE filesystem

### ISSUE THREAD

**Issue by Depau** [abraunegg/onedrive#88]
Use case: I have 1000TB OneDrive/Sharepoint which I would like to use to store my encrypted backups.
My plan is to incrementally store the latest snapshot in an ecryptfs filesystem, stored on OneDrive.

Of course I could create the filesystem locally and sync it using the existing tool, however I would have to duplicate all the data as backups are currently stored as Btrfs snapshots. With ecryptfs on OneDrive I would only have to rsync to the encrypted filesystem, uploading changes in real time.

https://github.com/facebook/dfuse
http://www.maastaar.net/fuse/linux/filesystem/c/2016/05/21/writing-a-simple-filesystem-using-fuse/

**Comment by Rondom** [comment]
Have you looked into rclone-mount?

**Comment by abraunegg** [comment]
Firstly - I hope that your snapshots in btrfs is working as expected. For data integrity I would be using ZFS on Linux (ZoL) rather than btrfs - but thats your call.

Secondly, I don't know how btrfs is doing the snapshots, however with ZoL you could take the snapshot, then send & receive that to a local file. Using rclone, you could have that then mounted to OneDrive where it is automatically sync'd or just run a onedrive sync process to upload.

If your looking for a reference implementation here - have a look at how I implemented this in MyNAS - www.mynas.com.au - where you have encryption at rest & sync to the cloud either the encrypted files & so on. Whilst it is not syncing the snapshots (because the system is not doing a send & receive to a local file) that could be implemented. in your use case to deliver the desired outcome.

**Comment by Depau** [comment]
The way I handle the snapshot is irrelevant, btrfs is doing a great job.
What I'm interested in here is a way to mount a remote OneDrive/SharePoint directory locally.

@Rondom no, never seen that but it seems to be exactly what I'm looking for. I'll look into it, thanks!

**Comment by abraunegg** [comment]
Closing as this is the same use case as https://github.com/abraunegg/onedrive/issues/84 for which there is an alternate solution - rclone - which can remove mount systems as WebDav devices.
