### ISSUE TITLE
docker hub tagging format

### ISSUE THREAD

**Issue by dhjensen** [abraunegg/onedrive#900]
**Is your feature request related to a problem? Please describe.**
It's difficult to find a specific version of onedrive on docker hub as only distro, date, hour and minutes are added to the tag. I assume this to be related to the docker post hook shell scrip used:
contrib/docker/hooks/post_push

**Describe the solution you'd like**
Tags with release info like "v2.4.0" for each distro type

**Additional context**
Me searching for version 2.4.0 using the date and hoping the latest tag from the date 23/03-20 is version 2.4.0.
![image](https://user-images.githubusercontent.com/26007707/80635954-f9c0ae00-8a5c-11ea-82e4-ade686e79794.png)

**Comment by abraunegg** [comment]
@dhjensen 
Thanks for pointing this out. The build rules for 'releases' were missing, and for some reason it has an issue with the regex for 'Source' so will have to always manually go back and add these in - unless you can suggest a fix:
![Docker_Build_Rules](https://user-images.githubusercontent.com/4956234/80688181-c3dc0200-8b0e-11ea-91e4-158228c05e03.JPG)

There also will not be a v2.4.0 for apline either, due to #850, which was fixed in #855, but there should be a v2.4.1 when that is released and the build rules get added (or updated to a regex that works).

**Comment by abraunegg** [comment]
@dhjensen 
The available v2.4.0 builds are there as per below now:
![docker_builds_v2 4 0](https://user-images.githubusercontent.com/4956234/80688871-d440ac80-8b0f-11ea-8877-772ad037bde1.JPG)

**Comment by dhjensen** [comment]
@abraunegg Thank you :),
I will use these builds. 

Unfortunately I'm not familiar with the docker hub auto-build and publish features.

A quick google is the best I got if you find that useful: [link](https://medium.com/better-programming/build-your-docker-images-automatically-when-you-push-on-github-18e80ece76af)

Here they use this `/^[0-9.]+$/` regex in source tag

**Comment by abraunegg** [comment]
@dhjensen 
Will see how / if this auto-builds for the next release ..

**Comment by abraunegg** [comment]
@dhjensen 
v2.4.1 should now be available on Docker

**Updated Build Rules:**
![updated_rules](https://user-images.githubusercontent.com/4956234/80839988-b2464780-8c3f-11ea-8a19-b6614517c960.JPG)


**Successful Builds:**
![results](https://user-images.githubusercontent.com/4956234/80839998-b5413800-8c3f-11ea-845e-6ccd5ba61b2b.JPG)

**Comment by dhjensen** [comment]
Thank you much better :)
