### ISSUE TITLE
“--synchronize --single-directory --download-only”  Wait too long

### ISSUE THREAD

**Issue by zplzpl** [abraunegg/onedrive#925]
my store 500 GB.

```
onedrive --synchronize --single-directory 'dir1/dir2/dir3' --download-only --no-remote-delete --confdir="~/.config/test"
```

the command runs for a long time.

how to improve..

i append " --verbose --dry-run" option,it show many:

```
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
........................................................
```

**Comment by abraunegg** [comment]
@zplzpl 
Please can you follow the correct process to report issues - https://github.com/abraunegg/onedrive#reporting-issues

Slow processing could be many things:
* Older code version
* CPU load
* Memory constraint
* I/O constraint
* Internet bandwidth constraint

Because your post does not include any details it is hard to assist. Update your post with the required information from the 'new issue template' here: https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md
