### ISSUE TITLE
Can not enable onedrive service with systemd

### ISSUE THREAD

**Issue by toanphuong** [abraunegg/onedrive#973]
```
(dmd-2.092.1)[pnguyentoan@tp480c onedrive]$ sudo make install
[sudo] password for pnguyentoan: 
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md docs/BusinessSharedFolders.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/system
/usr/bin/install -c -D -m 644 contrib/completions/complete.zsh /usr/local/share/zsh/site-functions/_onedrive
/usr/bin/install -c -D -m 644 contrib/completions/complete.bash /usr/share/bash-completion/completions/onedrive
(dmd-2.092.1)[pnguyentoan@tp480c onedrive]$ 
```
```
**systemctl --user enable onedrive
Failed to enable unit: Unit file onedrive.service does not exist.**
```

```
system: 4.18.0-193.6.3.el8_2.x86_64
(dmd-2.092.1)[pnguyentoan@tp480c onedrive]$ 
```

**Comment by Brli** [comment]
use `systemd enable onedrive@<your username>` instead.

**Comment by abraunegg** [comment]
@toanphuong 
Please can you update your first post with the required details as per the issue template: https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md 

**Assumption:**
Because of not using the issue template, I have to assume you are running on RHEL / CentOS because of the following:
```
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /usr/lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/system
```
RHEL / CentOS version of systemd does not support the `--user` directive. To use the service file, on RHEL / CentOS, refer to the following:
* [OneDrive service running as root user via systemd](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-root-user-via-systemd-red-hat-enterprise-linux-centos-linux)
* [OneDrive service running as a non-root user via systemd](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-without-notifications-or-gui)

The documentation is a little 'unclear' - so will need to get that updated.

@Brli is correct with the response above to resolve your issue.

**Comment by abraunegg** [comment]
Closing issue as questioned answered
