### ISSUE TITLE
can not download the file in the onedrive

### ISSUE THREAD

**Issue by amwps290** [abraunegg/onedrive#975]
My OS manjaro 

this is the output:
``` 
??:? void onedrive.OneDriveApi.checkHttpCode() [0xc57e61f3]
??:? void onedrive.OneDriveApi.download(const(char)[], immutable(char)[]) [0xc57e5abe]
??:? void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[]) [0xc57e4a43]
??:? void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0xc57efed1]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0xc57efa78]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0xc57ef90d]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0xc57ef0b7]
??:? void sync.SyncEngine.applyDifferences() [0xc57eed95]
??:? void main.performSync(sync.SyncEngine) [0xc57dd88f]
??:? _Dmain [0xc57dd3f3]
```

**Comment by abraunegg** [comment]
@amwps290 
Please can you follow the directions as per: https://github.com/abraunegg/onedrive#reporting-issues

Your post above is lacking critical details to assist, such as:
* What application version you are running
* How did you install - via package or compile?
* If compile, what compiler did you use
* What OneDrive account type you use
* What Curl version are you using

Please update your post with these details so that I can assist you - as the output you have provided is totally meaningless and unhelpful in its current context.

**Comment by abraunegg** [comment]
@amwps290 
Also, due to this line in your provided output:
```
??:? void main.performSync(sync.SyncEngine) [0xc57dd88f]
```

This is 100% inconsistent with the options that are passed in fro that function, which, if in error, would appear similar to this:
```
src/main.d:620 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x56301dd7fb3c]
```

The error you are facing is *most* likely due to the fact you are running the 'skilion' code and not this client.

**Comment by abraunegg** [comment]
Closing issue as 100% most likely 'skilion' code version. To resolve, upgrade your client.
